/**
 * Auto-generated by constants/sync-global-constants.mjs — do not edit by hand.
 * Source of truth: constants/global-constant-*.txt (one value per file).
 */
/** SSOT: `global-constant-bitcode-repository-url.txt` */
export const GLOBAL_CONSTANT_BITCODE_REPOSITORY_URL = "https://github.com/advancedengineeredsoftware/Bitcode" as const;

/** SSOT: `global-constant-bitcode-whitepaper-url.txt` */
export const GLOBAL_CONSTANT_BITCODE_WHITEPAPER_URL = "https://github.com/advancedengineeredsoftware/Bitcode/blob/version/v48/Whitepaper.md" as const;

/** SSOT: `global-constant-bitcode-x-url.txt` */
export const GLOBAL_CONSTANT_BITCODE_X_URL = "https://x.com/bitcodehq" as const;
