export interface GenerateDigestOptions {
  owner: string;
  repo: string;
  commit: string;
  correlationId?: string;
  usePreClonedRepo?: boolean;
  rootDir?: string;
  forceRegenerate?: boolean;
}

export interface GenerateDigestResult {
  productDocument?: string;
  agentDocument?: string;
}

export async function generateDigest(_options: GenerateDigestOptions): Promise<GenerateDigestResult> {
  return {
    productDocument: '###### What is this document?\n\nMock PRODUCT.md generated by digest.',
    agentDocument: '###### What is this document?\n\nMock AGENTS.md generated by digest.'
  };
}
