"use strict";

function transformDocCodeTools(source, filename) {
  const toolClassRegex = /\/\*\*([\s\S]*?)@doc-code-tool([\s\S]*?)\*\/\s*class\s+(\w+)\s+extends\s+Tool/g;
  const toolInstantiationRegex = /export\s+const\s+(\w+)\s*=\s*new\s+(\w+)\(\);?/g;
  const promptPattern = /@prompt\s+(\w+)/;

  const toolPromptMap = new Map();
  let match;

  while ((match = toolClassRegex.exec(source)) !== null) {
    const afterTag = match[2];
    const className = match[3];

    const promptMatch = promptPattern.exec(afterTag);
    if (!promptMatch) {
      console.warn(`[doc-code-tool-loader] No @prompt found for ${className} in ${filename}`);
      continue;
    }

    toolPromptMap.set(className, promptMatch[1]);
  }

  if (toolPromptMap.size === 0) {
    return source;
  }

  let transformedSource = source;
  toolInstantiationRegex.lastIndex = 0;

  while ((match = toolInstantiationRegex.exec(source)) !== null) {
    const varName = match[1];
    const className = match[2];
    const promptName = toolPromptMap.get(className);

    if (!promptName) {
      continue;
    }

    const assignmentAlreadyPresent = new RegExp(`\\(${varName}\\s+as\\s+any\\)\\.__docCodePrompt`).test(transformedSource);
    if (assignmentAlreadyPresent) {
      continue;
    }

    const matchedInstantiation = match[0];
    const originalStatement = matchedInstantiation.endsWith(';') ? matchedInstantiation : `${matchedInstantiation};`;
    const replacement = `${originalStatement}

// Attach DocCodeToolPrompt for runtime injection (auto-generated by doc-code-tool-loader)
;(${varName} as any).__docCodePrompt = ${promptName};
;(${varName} as any).__promptParts = ${promptName};`;

    transformedSource = transformedSource.replace(matchedInstantiation, replacement);
  }

  return transformedSource;
}

module.exports = {
  transformDocCodeTools,
};
