/**
 * Business logic utilities for conversations
 * 
 * Pure functions that operate on conversation data
 * No database access - that's in ORM package
 */

import {
  Conversation,
  ConversationMessage,
  MessageAttachment,
  ConversationWithStats,
  MessageWithDetails
} from './types';

/**
 * Generate a default conversation title from first message
 */
export function generateConversationTitle(firstMessage: string): string {
  // Truncate to reasonable length for title
  const maxLength = 100;
  const cleaned = firstMessage.trim().replace(/\s+/g, ' ');
  
  if (cleaned.length <= maxLength) {
    return cleaned;
  }
  
  // Find last complete word before limit
  const truncated = cleaned.substring(0, maxLength);
  const lastSpace = truncated.lastIndexOf(' ');
  
  if (lastSpace > 50) {
    return truncated.substring(0, lastSpace) + '...';
  }
  
  return truncated + '...';
}

/**
 * Calculate conversation statistics from messages and attachments
 */
export function calculateConversationStats(
  conversation: Conversation,
  messages: ConversationMessage[],
  attachments: MessageAttachment[]
): ConversationWithStats {
  const lastMessage = messages[messages.length - 1];
  
  return {
    ...conversation,
    message_count: messages.length,
    last_message_content: lastMessage?.content,
    last_message_at: lastMessage?.created_at,
    attachment_count: attachments.length
  };
}

/**
 * Group messages by date for UI display
 */
export function groupMessagesByDate(messages: ConversationMessage[]): Map<string, ConversationMessage[]> {
  const groups = new Map<string, ConversationMessage[]>();
  
  messages.forEach(message => {
    const date = new Date(message.created_at);
    const dateKey = date.toISOString().split('T')[0]; // YYYY-MM-DD
    
    if (!groups.has(dateKey)) {
      groups.set(dateKey, []);
    }
    
    groups.get(dateKey)!.push(message);
  });
  
  return groups;
}

/**
 * Format message for display (truncate, sanitize, etc)
 */
export function formatMessageForDisplay(message: ConversationMessage, maxLength = 200): string {
  let content = message.content.trim();
  
  // Remove excessive whitespace
  content = content.replace(/\s+/g, ' ');
  
  // Truncate if needed
  if (content.length > maxLength) {
    content = content.substring(0, maxLength) + '...';
  }
  
  return content;
}

/**
 * Determine if a conversation is active (recent activity)
 */
export function isConversationActive(conversation: Conversation, inactiveThresholdHours = 24): boolean {
  const lastUpdate = new Date(conversation.updated_at);
  const now = new Date();
  const hoursSinceUpdate = (now.getTime() - lastUpdate.getTime()) / (1000 * 60 * 60);
  
  return hoursSinceUpdate < inactiveThresholdHours;
}

/**
 * Extract entity references from a message
 */
export function extractMessageReferences(
  _message: ConversationMessage,
  attachments: MessageAttachment[] = []
): { hasReferences: boolean } {
  // Bitcode V26 stores references in message_attachments; message rows do not carry FK refs.
  return { hasReferences: attachments.length > 0 };
}

/**
 * Sort conversations by activity (most recent first)
 */
export function sortConversationsByActivity(conversations: ConversationWithStats[]): ConversationWithStats[] {
  return [...conversations].sort((a, b) => {
    const dateA = new Date(a.last_message_at || a.updated_at);
    const dateB = new Date(b.last_message_at || b.updated_at);
    return dateB.getTime() - dateA.getTime();
  });
}

/**
 * Filter conversations by search term
 */
export function filterConversationsBySearch(
  conversations: ConversationWithStats[],
  searchTerm: string
): ConversationWithStats[] {
  const lowerSearch = searchTerm.toLowerCase();
  
  return conversations.filter(conv => 
    conv.title.toLowerCase().includes(lowerSearch) ||
    conv.last_message_content?.toLowerCase().includes(lowerSearch)
  );
}

/**
 * Check if user can perform action on conversation
 * (For now just checks user_id match, can be extended)
 */
export function canUserAccessConversation(
  conversation: Conversation,
  userId: string
): boolean {
  return conversation.user_id === userId;
}

/**
 * Create a system message for conversation events
 */
export function createSystemMessage(
  conversationId: string,
  event: 'created' | 'asset_pack_evidence_attached' | 'evidence_document_attached' | 'connection_attached',
  metadata?: Record<string, any>
): ConversationMessage {
  const messages: Record<typeof event, string> = {
    created: 'Conversation started',
    asset_pack_evidence_attached: 'AssetPack evidence attached to conversation',
    evidence_document_attached: 'Evidence Document attached to conversation',
    connection_attached: 'Connection attached to conversation'
  };
  
  return {
    id: '', // Will be generated by DB
    conversation_id: conversationId,
    role: 'assistant',
    content: messages[event],
    created_at: new Date().toISOString()
  };
}
