/**
 * DOC-CODE-TOOL WEBPACK LOADER
 * 
 * Webpack loader for build-time transformation of @doc-code-tool comments
 * This runs during module loading, before TypeScript compilation
 */

import type { LoaderContext } from 'webpack';

export interface DocCodeToolLoaderOptions {
  test?: RegExp;
  exclude?: RegExp[];
}

/**
 * Webpack loader for doc-code-tool transformation
 */
export default function docCodeToolLoader(
  this: LoaderContext<DocCodeToolLoaderOptions>,
  source: string
): string {
  const options = this.getOptions() || {};
  
  // Skip if file doesn't match test pattern
  if (options.test && !options.test.test(this.resourcePath)) {
    return source;
  }
  
  // Skip if file matches exclusion patterns
  if (options.exclude?.some(pattern => pattern.test(this.resourcePath))) {
    return source;
  }
  
  // Quick check for @doc-code-tool to avoid processing files without it
  if (!source.includes('@doc-code-tool')) {
    return source;
  }
  
  try {
    const transformed = transformDocCodeTools(source, this.resourcePath);
    return transformed;
  } catch (error) {
    this.emitError(error as Error);
    return source;
  }
}

/**
 * Transform source code to inject doc-code-tool attachments
 */
function transformDocCodeTools(source: string, filename: string): string {
  // Pattern to match Tool classes with @doc-code-tool comments
  const toolClassRegex = /\/\*\*([\s\S]*?)@doc-code-tool([\s\S]*?)\*\/\s*class\s+(\w+)\s+extends\s+Tool/g;
  const toolInstantiationRegex = /export\s+const\s+(\w+)\s*=\s*new\s+(\w+)\(\)/g;
  const promptPattern = /@prompt\s+(\w+)/;
  
  // Find all tool classes with @doc-code-tool comments
  const toolPromptMap = new Map<string, string>();
  let match;
  
  while ((match = toolClassRegex.exec(source)) !== null) {
    const fullComment = match[0];
    const beforeTag = match[1];
    const afterTag = match[2];
    const className = match[3];
    
    // Extract @prompt field
    const promptMatch = promptPattern.exec(afterTag);
    if (!promptMatch) {
      console.warn(`[doc-code-tool-loader] No @prompt found for ${className} in ${filename}`);
      continue;
    }
    
    const promptName = promptMatch[1];
    toolPromptMap.set(className, promptName);
  }
  
  // No tools found, return original
  if (toolPromptMap.size === 0) return source;
  
  // Transform tool instantiations
  let transformedSource = source;
  toolInstantiationRegex.lastIndex = 0;
  
  while ((match = toolInstantiationRegex.exec(source)) !== null) {
    const varName = match[1];
    const className = match[2];
    const promptName = toolPromptMap.get(className);
    
    if (promptName) {
      const assignmentAlreadyPresent = new RegExp(`\\(${varName}\\s+as\\s+any\\)\\.__docCodePrompt`).test(transformedSource);
      if (assignmentAlreadyPresent) {
        continue;
      }

      const originalMatch = match[0];
      const replacement = `${originalMatch}

// Attach DocCodeToolPrompt for runtime injection (auto-generated by doc-code-tool-loader)
(${varName} as any).__docCodePrompt = ${promptName};`;
      
      transformedSource = transformedSource.replace(originalMatch, replacement);
    }
  }
  
  return transformedSource;
}

// TypeScript declaration for webpack
export const raw = false;
