/**
 * Docs content module: api reference mcp.
 */
import type { DocsInterfaceApiSection } from '../bitcode-docs-types';

export const mcpApiReference = [
  {
    id: 'mcp-call-lifecycle',
    title: 'MCP call lifecycle',
    summary:
      'The proof-readback MCP server exposes tools/list and tools/call over the Model Context Protocol, authenticates each call, applies rate/resource limits, and dispatches by bitcode:// prefix.',
    packagePath: 'apps/mcp/src/server.ts',
    features: [
      {
        name: 'tools/list',
        method: 'MCP request',
        packagePath: 'apps/mcp/src/server.ts',
        useWhen: 'Discover the active default Bitcode MCP tools available to a client.',
        howToUse:
          'Call tools/list after connecting. The default server registers pipeline, analysis, intelligence, enterprise, LSP, and observability categories.',
        inputs: ['No body is required for discovery.'],
        outputs: [
          'tools: array of { name, description, inputSchema } records.',
          'Server logs include count and failed category count.',
        ],
      },
      {
        name: 'tools/call',
        method: 'MCP request',
        packagePath: 'apps/mcp/src/server.ts',
        useWhen: 'Execute one proof-readback MCP feature.',
        howToUse:
          'Pass name and arguments. Include request params _meta.authorization when auth is required. Local repositories are prepared before execution when repository.provider is local.',
        inputs: [
          'name: required bitcode:// tool identifier.',
          'arguments: tool-specific validated input object.',
          '_meta.authorization: optional auth header used by authenticateMCPRequest.',
        ],
        outputs: [
          'Tool-specific result object.',
          'Execution passes through auth, rate limits, resource limits, and circuit breaker handling.',
        ],
        failureModes: [
          'Authentication failure rejects the call.',
          'Invalid schema arguments return validation errors.',
          'Unknown tool names fail closed.',
        ],
      },
    ],
  },
  {
    id: 'mcp-pipeline-tools',
    title: 'Pipeline tools',
    summary:
      'Pipeline tools write bounded AssetPack intent into route-facing execution, require pipeline create permission, and return rereadable run/admission metadata.',
    packagePath: 'apps/mcp/src/tools/pipeline-tools.ts',
    features: [
      {
        name: 'bitcode://pipelines/asset-pack/create',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/pipeline-tools.ts',
        useWhen: 'Create an AssetPack pipeline for implementation, review, issue work, docs, diagrams, API specs, scaffolding, planning, or refactoring.',
        howToUse:
          'Pass task, repository, subtype, and optional attachments/connections. Use streaming for queued run reread or wait for completion when streaming is false.',
        inputs: [
          'task: required detailed task, minimum 10 characters.',
          'repository: required RepositoryContext, including provider/owner/name/branch or local path.',
          'subtype: pull_request, pr_review, issue, comment, blog_post, diagram, api_spec, frontend_scaffolder, scope_analysis, implementation_plan, or refactor_proposal.',
          'attachments: optional multimodal source context.',
          'connections: optional repository/provider ingress context.',
          'mcpConfig, streaming, organizationId, modelPreferences, and options.',
        ],
        outputs: [
          'runId and assetPackEvidenceId.',
          'status, interfaceSurface, inputContext, writeAdmission, and outputMeaning.',
          'When completed: result, AssetPack synthesis artifacts, Shippables, measuredBtd, BTC-fee posture, timestamps, and events.',
        ],
        verifyInProduct: 'Open the returned run/activity and inspect AssetPack, proof, delivery, and settlement posture.',
        failureModes: [
          'Requires pipelines.create permission.',
          'Rejects incoherent repository_connection ingress.',
          'Rejects non-local providers without matching connection or provider credential.',
        ],
        requiresConfirmation: true,
      },
    ],
  },
  {
    id: 'mcp-analysis-tools',
    title: 'Analysis tools',
    summary:
      'Analysis tools read repository, dependency, pattern, and trend evidence for route and interface users.',
    packagePath: 'apps/mcp/src/tools/analysis-tools.ts',
    features: [
      {
        name: 'bitcode://analysis/repository/analyze',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/analysis-tools.ts',
        useWhen: 'Analyze one repository for architecture, dependencies, security, performance, quality, complexity, patterns, or technical debt.',
        howToUse: 'Pass repository coordinates, analysisType, and optional depth/output controls.',
        inputs: [
          'repository: { owner, name, branch? }.',
          'analysisType: architecture, dependencies, security, performance, quality, complexity, patterns, or technical_debt.',
          'depth: surface, medium, or deep.',
          'includeMetrics and outputFormat.',
        ],
        outputs: ['repository, branch, analysisType, timestamp, analyst.', 'results and metadata with analysisId, duration, confidence, lines/files analyzed.'],
      },
      {
        name: 'bitcode://analysis/intelligence/synthesize',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/analysis-tools.ts',
        useWhen: 'Synthesize trends across repository, organization, or user scope.',
        howToUse: 'Pass scope/timeframe and optional repositories, analysisTypes, recommendation, and confidence settings.',
        inputs: [
          'scope: repository, organization, or user.',
          'timeframe: 7d, 30d, 90d, or all.',
          'repositories and analysisTypes.',
          'includeRecommendations and confidenceThreshold.',
        ],
        outputs: ['insights, recommendations, trends, and metadata.', 'Confidence-scored strategic guidance for engineering decisions.'],
      },
      {
        name: 'bitcode://analysis/patterns/detect',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/analysis-tools.ts',
        useWhen: 'Find design patterns, anti-patterns, architecture patterns, testing patterns, security patterns, or performance patterns.',
        howToUse: 'Pass repository/path plus pattern type filters and severity.',
        inputs: [
          'repository: { owner, name, path? }.',
          'patternTypes: optional array.',
          'language, includeExamples, and severity.',
        ],
        outputs: ['patterns with type, name, confidence, locations, examples, severity, and recommendations.', 'summary totals and average confidence.'],
      },
      {
        name: 'bitcode://analysis/dependencies/analyze',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/analysis-tools.ts',
        useWhen: 'Analyze dependency graph, vulnerabilities, licenses, updates, and dependency risk.',
        howToUse: 'Pass repository plus depth and inclusion toggles.',
        inputs: [
          'repository: { owner, name }.',
          'analysisDepth: direct, transitive, or full.',
          'includeVulnerabilities, includeLicenses, includeUpdates.',
          'outputFormat: json, graph, or report.',
        ],
        outputs: ['dependency counts, vulnerabilities, license summary, update recommendations, and risk posture.'],
      },
    ],
  },
  {
    id: 'mcp-intelligence-tools',
    title: 'Intelligence tools',
    summary:
      'Intelligence tools turn measured code, repositories, research, and attachments into higher-level recommendations.',
    packagePath: 'apps/mcp/src/tools/intelligence-tools.ts',
    features: [
      {
        name: 'bitcode://intelligence/effectiveness/track',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/intelligence-tools.ts',
        useWhen: 'Measure, predict, learn, or optimize code-change effectiveness.',
        howToUse: 'Choose operation and provide the matching metrics, proposedChanges, outcomes, or targetMetrics.',
        inputs: ['operation: measure, predict, learn, or optimize.', 'pipelineId, beforeMetrics, afterMetrics, repository, proposedChanges, outcomes, targetMetrics, constraints, timeframe, includeConfidence.'],
        outputs: ['Effectiveness scores, predictions, learning results, or optimization recommendations with confidence data.'],
      },
      {
        name: 'bitcode://intelligence/cross-repo/learn',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/intelligence-tools.ts',
        useWhen: 'Extract, propagate, analyze, or recommend cross-repository patterns.',
        howToUse: 'Choose operation and provide source repositories, patterns, targets, analysisType, or repositoryContext.',
        inputs: ['operation: extract, propagate, analyze, or recommend.', 'sourceRepositories, patterns, targetRepositories, analysisType, repositoryContext, includeVisualization, maxResults.'],
        outputs: ['Extracted patterns, propagation results, cross-repo insights, visualization data, and recommendations.'],
      },
      {
        name: 'bitcode://intelligence/research/advanced',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/intelligence-tools.ts',
        useWhen: 'Run multi-provider research with URL credibility and synthesis.',
        howToUse: 'Pass a detailed query, researchType, provider list, filters, and synthesis options.',
        inputs: ['query, researchType, providers, filters, synthesisType, maxResults, includeUrlIntelligence, contextAware.'],
        outputs: ['research_results, synthesis, url_intelligence, and credibility_scores.'],
      },
      {
        name: 'bitcode://intelligence/multimodal/process',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/intelligence-tools.ts',
        useWhen: 'Process images, audio, video, documents, Figma files, or URLs into technical knowledge evidence.',
        howToUse: 'Pass at least one attachment, a processingType, and desired output format/synthesis settings.',
        inputs: ['attachments: array of { type, content, metadata? }.', 'processingType, outputFormat, crossModalSynthesis, includeImplementationGuidance, contextRepository, qualityThreshold.'],
        outputs: ['processed_attachments, synthesis, implementation_guidance, and quality_scores.'],
      },
      {
        name: 'bitcode://intelligence/enterprise/orchestrate',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/intelligence-tools.ts',
        useWhen: 'Analyze team, organization, knowledge, skill-gap, collaboration, innovation, risk, or strategy posture.',
        howToUse: 'Pass operation, organizationId, scope, time horizon, depth, recommendation, benchmarking, and confidentiality settings.',
        inputs: ['operation, organizationId, scope, timeHorizon, analysisDepth, includeRecommendations, includeBenchmarking, confidentialityLevel.'],
        outputs: ['analysis, strategic_insights, benchmarking, and recommendations.'],
      },
      {
        name: 'bitcode://intelligence/marketplace/analyze',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/intelligence-tools.ts',
        useWhen: 'Discover, assess, price, or risk-review marketplace solutions and providers.',
        howToUse: 'Choose marketplace operation and provide requirements, listing/provider IDs, search query, filters, and risk settings.',
        inputs: ['operation, requirements, listingId, providerId, searchQuery, filters, includeCompetitiveAnalysis, riskTolerance.'],
        outputs: ['solutions, quality_assessment, provider_analysis, and recommendations.'],
      },
    ],
  },
  {
    id: 'mcp-enterprise-tools',
    title: 'Enterprise interface tools',
    summary:
      'Enterprise tools configure webhooks, managed APIs, integration marketplace connectors, and observability surfaces.',
    packagePath: 'apps/mcp/src/tools/enterprise-tools.ts',
    features: [
      {
        name: 'bitcode://enterprise/webhook/orchestrate',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/enterprise-tools.ts',
        useWhen: 'Create, update, delete, test, route, batch, or inspect enterprise webhooks.',
        howToUse: 'Pass operation and the webhook/routing/test/analytics payload that matches it.',
        inputs: ['operation plus webhook config, testPayload, analyticsTimeRange, webhookIds, or routingRules.'],
        outputs: ['Webhook operation result, analytics, delivery status, routing results, or audit-ready recommendations.'],
      },
      {
        name: 'bitcode://enterprise/api/manage',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/enterprise-tools.ts',
        useWhen: 'Manage API lifecycle: create, version, deploy, govern, document, rate-limit, monitor, or test APIs.',
        howToUse: 'Pass operation and API config, environment, versioning strategy, governance rules, or test suite.',
        inputs: ['operation plus api, versioningStrategy, environment, governanceRules, or testSuite.'],
        outputs: ['API operation result, governance score, documentation output, analytics, or test report.'],
      },
      {
        name: 'bitcode://enterprise/integration/marketplace',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/enterprise-tools.ts',
        useWhen: 'Browse, install, configure, update, uninstall, analyze, develop, or publish enterprise integrations.',
        howToUse: 'Pass operation and the relevant marketplace, integration, connector, or filter payload.',
        inputs: ['operation plus filters, integration config, connector config, dataMapping, triggers, schedule, or tests.'],
        outputs: ['integrations, marketplace_analytics, installation_status, and custom_connectors.'],
      },
      {
        name: 'bitcode://enterprise/observability/configure',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/enterprise-tools.ts',
        useWhen: 'Configure metrics, traces, logs, alerts, dashboards, and analysis settings for enterprise observability.',
        howToUse: 'Pass monitoringConfig, alerts, dashboard, and analysisConfig.',
        inputs: ['monitoringConfig, alerts, dashboard, analysisConfig.'],
        outputs: ['monitoring_status, dashboards, alerts, telemetry_endpoints, and related configuration results.'],
      },
    ],
  },
  {
    id: 'mcp-lsp-tools',
    title: 'LSP and code-intelligence tools',
    summary:
      'LSP tools provide semantic analysis, navigation/refactoring, diagnostics, and workspace-wide intelligence.',
    packagePath: 'apps/mcp/src/tools/lsp-tools.ts',
    features: [
      {
        name: 'bitcode://lsp/semantic/analyze',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/lsp-tools.ts',
        useWhen: 'Analyze symbols, types, dependency graphs, call graphs, semantic search, hover, or signatures.',
        howToUse: 'Pass repository, targets, optional position, analysisConfig, and filters.',
        inputs: ['repository, targets, position, analysisConfig, filters.'],
        outputs: ['Semantic analysis, symbol relationships, dependency/call graph data, and contextual code intelligence.'],
      },
      {
        name: 'bitcode://lsp/intelligence/navigate',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/lsp-tools.ts',
        useWhen: 'Find references, rename symbols, extract methods, find implementations, get actions, or organize imports.',
        howToUse: 'Pass repository, symbol target, refactoring config, optional range, and formatting options.',
        inputs: ['repository, symbol, refactoringConfig, range, formattingOptions.'],
        outputs: ['references, rename or refactor previews, implementations, code actions, quick fixes, and source actions.'],
      },
      {
        name: 'bitcode://lsp/diagnostic/analyze',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/lsp-tools.ts',
        useWhen: 'Run diagnostics across syntax, semantics, performance, security, complexity, tests, or dependencies.',
        howToUse: 'Pass repository, scope, diagnosticConfig, thresholds, preferences, and outputConfig.',
        inputs: ['repository, scope, diagnosticConfig, qualityThresholds, analysisPreferences, outputConfig.'],
        outputs: ['diagnostics, quality_score, recommendations, and metrics.'],
      },
      {
        name: 'bitcode://lsp/workspace/intelligence',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/lsp-tools.ts',
        useWhen: 'Understand architecture, module dependencies, API surface, change impact, technical debt, and knowledge graph.',
        howToUse: 'Pass repository, analysisScope, changeAnalysis, architectureConfig, knowledgeGraphConfig, migrationConfig, and visualizationConfig.',
        inputs: ['repository, analysisScope, changeAnalysis, architectureConfig, knowledgeGraphConfig, migrationConfig, visualizationConfig.'],
        outputs: ['workspace_analysis, architecture_insights, knowledge_graph, and recommendations.'],
      },
    ],
  },
  {
    id: 'mcp-observability-tools',
    title: 'Observability tools',
    summary:
      'Observability tools read and configure metrics, traces, business intelligence, and log analytics.',
    packagePath: 'apps/mcp/src/tools/observability-tools.ts',
    features: [
      {
        name: 'bitcode://observability/metrics/realtime',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/observability-tools.ts',
        useWhen: 'Collect/query metrics, configure alerts, build dashboards, or stream real-time data.',
        howToUse: 'Pass metrics, query, alert, dashboard, and streamConfig depending on the operation.',
        inputs: ['metrics, query, alert, dashboard, streamConfig.'],
        outputs: ['metrics result, alert status, dashboard data, stream configuration, anomalies, and benchmarks.'],
      },
      {
        name: 'bitcode://observability/tracing/distributed',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/observability-tools.ts',
        useWhen: 'Analyze distributed traces, spans, service maps, profiling, bottlenecks, and request flow.',
        howToUse: 'Pass trace/span data and analysis, profiling, and service-map config.',
        inputs: ['trace, span, analysisConfig, profilingConfig, serviceMapConfig.'],
        outputs: ['trace analysis, bottlenecks, dependencies, health, and visualization data.'],
      },
      {
        name: 'bitcode://observability/intelligence/business',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/observability-tools.ts',
        useWhen: 'Read technical productivity, ROI, technical debt cost, velocity, quality, innovation, and benchmark metrics.',
        howToUse: 'Pass scope, metricsConfig, analysisPreferences, outputConfig, and benchmarkConfig.',
        inputs: ['scope, metricsConfig, analysisPreferences, outputConfig, benchmarkConfig.'],
        outputs: ['metrics, insights, recommendations, and forecasts.'],
      },
      {
        name: 'bitcode://observability/logs/analytics',
        method: 'tools/call',
        packagePath: 'apps/mcp/src/tools/observability-tools.ts',
        useWhen: 'Run log search, pattern detection, anomaly analysis, security analysis, or compliance reporting.',
        howToUse: 'Pass logs or searchQuery with analysis, pattern, anomaly, and compliance config.',
        inputs: ['logs, analysisConfig, searchQuery, patternConfig, anomalyConfig, complianceConfig.'],
        outputs: ['analysis, patterns, anomalies, compliance, and correlated log intelligence.'],
      },
    ],
  },
] as const satisfies readonly DocsInterfaceApiSection[];
