export interface BitcodeAppContext {
  handle(req: unknown, res: unknown): Promise<void>;
  getState(principal?: string): unknown;
  resetState(): unknown;
  getBitcoinDemonstrationService(): unknown;
  getExternalRealization(input?: Record<string, unknown>): unknown;
  getReadReview(input?: Record<string, unknown>): unknown;
  reviewRead(input?: Record<string, unknown>): unknown;
  createDeposit(input?: Record<string, unknown>): unknown;
  makeBitcodeBranch(input?: Record<string, unknown>): Promise<unknown>;
  executeLocalExecutorById(interfaceId: string, input?: Record<string, unknown>): Promise<unknown>;
}

export interface BitcodeServerOptions {
  dataPath?: string;
  publicDir?: string;
}

export const DEFAULT_BITCODE_DATA_PATH: string;
export const DEFAULT_BITCODE_PUBLIC_DIR: string;

export function createAppContext(options?: BitcodeServerOptions): BitcodeAppContext;

export function createServer(
  options?: BitcodeServerOptions,
): Promise<{ app: BitcodeAppContext; server: unknown }>;

export function startServer(
  options?: BitcodeServerOptions & { port?: number; host?: string },
): Promise<{ app: BitcodeAppContext; server: unknown; port: number; host: string }>;

export const ACTIVE_CANON_VERSION: string;
export const DRAFT_TARGET_VERSION: string;

export interface BitcodeProtocolReport {
  passed: boolean;
  [key: string]: unknown;
}

export interface BitcodeProvenMarkdownPackage {
  data: unknown;
  markdown: string;
  artifacts?: Record<string, unknown>;
  [key: string]: unknown;
}

export const PROVEN_GENERATOR_ID: string;

export function buildV21SpecFamilyReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export function buildV21CanonicalInputReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export function buildV21GeneratedArtifactContents(input?: Record<string, unknown>): unknown;
export function buildCanonPostureDriftReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export const EXCHANGE_ACTIVITY_BOOK_ARTIFACT_PATH: string;
export const EXCHANGE_ACTIVITY_BOOK_CURRENT_TARGET: string;
export const EXCHANGE_ACTIVITY_BOOK_SCHEMA_ID: string;
export const EXCHANGE_ACTIVITY_BOOK_VERSION: string;
export const EXCHANGE_ACTIVITY_BOOK_SOURCE_SAFETY_VERDICT: string;
export const EXCHANGE_ACTIVITY_KINDS: readonly string[];
export const EXCHANGE_ACTIVITY_FILTER_IDS: readonly string[];
export const EXCHANGE_ACTIVITY_DETAIL_SECTION_IDS: readonly string[];
export const EXCHANGE_ACTIVITY_ROWS: readonly Record<string, unknown>[];
export function buildExchangeActivityBook(input?: Record<string, unknown>): BitcodeProtocolReport;
export const CONVERSATION_SESSION_ROUTE_HISTORY_ARTIFACT_PATH: string;
export const CONVERSATION_SESSION_ROUTE_HISTORY_CURRENT_TARGET: string;
export const CONVERSATION_SESSION_ROUTE_HISTORY_SCHEMA_ID: string;
export const CONVERSATION_SESSION_ROUTE_HISTORY_VERSION: string;
export const CONVERSATION_SESSION_ROUTE_HISTORY_SOURCE_SAFETY_VERDICT: string;
export const CONVERSATION_SESSION_FIELD_IDS: readonly string[];
export const CONVERSATION_HISTORY_OPERATION_IDS: readonly string[];
export const CONVERSATION_SESSION_ROUTE_IDS: readonly string[];
export const CONVERSATION_SESSION_ROUTE_HISTORY_ROWS: readonly Record<string, unknown>[];
export function buildConversationSessionRouteHistory(input?: Record<string, unknown>): BitcodeProtocolReport;
export const CONVERSATION_STREAM_EVENT_CONTRACT_ARTIFACT_PATH: string;
export const CONVERSATION_STREAM_EVENT_CONTRACT_CURRENT_TARGET: string;
export const CONVERSATION_STREAM_EVENT_CONTRACT_SCHEMA_ID: string;
export const CONVERSATION_STREAM_EVENT_CONTRACT_VERSION: string;
export const CONVERSATION_STREAM_EVENT_CONTRACT_SOURCE_SAFETY_VERDICT: string;
export const CONVERSATION_STREAM_EVENT_KIND_IDS: readonly string[];
export const CONVERSATION_STREAM_REQUIRED_TELEMETRY_FIELD_IDS: readonly string[];
export const CONVERSATION_STREAM_DISCLOSURE_POSTURES: readonly string[];
export const CONVERSATION_STREAM_EVENT_CONTRACT_ROWS: readonly Record<string, unknown>[];
export function buildConversationStreamEventContract(input?: Record<string, unknown>): BitcodeProtocolReport;
export const CONVERSATION_WRITING_WORKSPACE_ARTIFACT_PATH: string;
export const CONVERSATION_WRITING_WORKSPACE_CURRENT_TARGET: string;
export const CONVERSATION_WRITING_WORKSPACE_SCHEMA_ID: string;
export const CONVERSATION_WRITING_WORKSPACE_VERSION: string;
export const CONVERSATION_WRITING_WORKSPACE_SOURCE_SAFETY_VERDICT: string;
export const CONVERSATION_WRITING_WORKSPACE_MODE_IDS: readonly string[];
export const CONVERSATION_WRITING_WORKSPACE_ACTION_IDS: readonly string[];
export const CONVERSATION_WRITING_WORKSPACE_FIELD_IDS: readonly string[];
export const CONVERSATION_WRITING_WORKSPACE_ROWS: readonly Record<string, unknown>[];
export function buildConversationWritingWorkspace(input?: Record<string, unknown>): BitcodeProtocolReport;
export const CONVERSATION_SOURCE_SELECTOR_ARTIFACT_PATH: string;
export const CONVERSATION_SOURCE_SELECTOR_CURRENT_TARGET: string;
export const CONVERSATION_SOURCE_SELECTOR_SCHEMA_ID: string;
export const CONVERSATION_SOURCE_SELECTOR_VERSION: string;
export const CONVERSATION_SOURCE_SELECTOR_SOURCE_SAFETY_VERDICT: string;
export const CONVERSATION_SOURCE_SELECTOR_KIND_IDS: readonly string[];
export const CONVERSATION_SOURCE_SELECTOR_GOVERNANCE_IDS: readonly string[];
export const CONVERSATION_SOURCE_SELECTOR_PREVIEW_STATES: readonly string[];
export const CONVERSATION_SOURCE_SELECTOR_FIELD_IDS: readonly string[];
export const CONVERSATION_SOURCE_SELECTOR_ROWS: readonly Record<string, unknown>[];
export function buildConversationSourceSelector(input?: Record<string, unknown>): BitcodeProtocolReport;
export const CONVERSATION_TERMINAL_HANDOFF_ARTIFACT_PATH: string;
export const CONVERSATION_TERMINAL_HANDOFF_CURRENT_TARGET: string;
export const CONVERSATION_TERMINAL_HANDOFF_SCHEMA_ID: string;
export const CONVERSATION_TERMINAL_HANDOFF_VERSION: string;
export const CONVERSATION_TERMINAL_HANDOFF_SOURCE_SAFETY_VERDICT: string;
export const CONVERSATION_TERMINAL_HANDOFF_WORKFLOW_IDS: readonly string[];
export const CONVERSATION_TERMINAL_HANDOFF_FIELD_IDS: readonly string[];
export const CONVERSATION_TERMINAL_HANDOFF_AUTHORITY_IDS: readonly string[];
export const CONVERSATION_TERMINAL_HANDOFF_POLICY_STATES: readonly string[];
export const CONVERSATION_TERMINAL_HANDOFF_ROWS: readonly Record<string, unknown>[];
export function buildConversationTerminalHandoff(input?: Record<string, unknown>): BitcodeProtocolReport;
export const CONVERSATION_PERSISTENCE_PRIVACY_ARTIFACT_PATH: string;
export const CONVERSATION_PERSISTENCE_PRIVACY_CURRENT_TARGET: string;
export const CONVERSATION_PERSISTENCE_PRIVACY_SCHEMA_ID: string;
export const CONVERSATION_PERSISTENCE_PRIVACY_VERSION: string;
export const CONVERSATION_PERSISTENCE_PRIVACY_SOURCE_SAFETY_VERDICT: string;
export const CONVERSATION_PERSISTENCE_VISIBILITY_TIER_IDS: readonly string[];
export const CONVERSATION_PERSISTENCE_OPERATION_IDS: readonly string[];
export const CONVERSATION_PERSISTENCE_RETENTION_POSTURES: readonly string[];
export const CONVERSATION_PERSISTENCE_FIELD_IDS: readonly string[];
export const CONVERSATION_PERSISTENCE_FORBIDDEN_PAYLOAD_CLASSES: readonly string[];
export const CONVERSATION_PERSISTENCE_PRIVACY_ROWS: readonly Record<string, unknown>[];
export function buildConversationPersistencePrivacyRedaction(input?: Record<string, unknown>): BitcodeProtocolReport;
export const CONVERSATION_TELEMETRY_PROOF_HOOKS_ARTIFACT_PATH: string;
export const CONVERSATION_TELEMETRY_PROOF_HOOKS_CURRENT_TARGET: string;
export const CONVERSATION_TELEMETRY_PROOF_HOOKS_SCHEMA_ID: string;
export const CONVERSATION_TELEMETRY_PROOF_HOOKS_VERSION: string;
export const CONVERSATION_TELEMETRY_PROOF_HOOKS_SOURCE_SAFETY_VERDICT: string;
export const CONVERSATION_TELEMETRY_EVENT_FAMILY_IDS: readonly string[];
export const CONVERSATION_TELEMETRY_REQUIRED_FIELD_IDS: readonly string[];
export const CONVERSATION_TELEMETRY_DASHBOARD_PANEL_IDS: readonly string[];
export const CONVERSATION_TELEMETRY_RUNBOOK_IDS: readonly string[];
export const CONVERSATION_TELEMETRY_FORBIDDEN_PAYLOAD_CLASSES: readonly string[];
export const CONVERSATION_TELEMETRY_PROOF_HOOK_ROWS: readonly Record<string, unknown>[];
export function buildConversationTelemetryProofHooks(input?: Record<string, unknown>): BitcodeProtocolReport;
export const CONVERSATION_REHEARSAL_ARTIFACT_PATH: string;
export const CONVERSATION_REHEARSAL_CURRENT_TARGET: string;
export const CONVERSATION_REHEARSAL_SCHEMA_ID: string;
export const CONVERSATION_REHEARSAL_VERSION: string;
export const CONVERSATION_REHEARSAL_SOURCE_SAFETY_VERDICT: string;
export const CONVERSATION_REHEARSAL_IDS: readonly string[];
export const CONVERSATION_REHEARSAL_FLOW_IDS: readonly string[];
export const CONVERSATION_REHEARSAL_ROWS: readonly Record<string, unknown>[];
export function buildConversationRehearsal(input?: Record<string, unknown>): BitcodeProtocolReport;
export const CONVERSATION_PROMOTION_READINESS_REPORT_ARTIFACT_PATH: string;
export const CONVERSATION_PROMOTION_READINESS_REPORT_CURRENT_TARGET: string;
export const CONVERSATION_PROMOTION_READINESS_REPORT_SCHEMA_ID: string;
export const CONVERSATION_PROMOTION_READINESS_REPORT_VERSION: string;
export const CONVERSATION_PROMOTION_READINESS_SOURCE_SAFETY_VERDICT: string;
export const CONVERSATION_PROMOTION_READINESS_GATE_ARTIFACT_PATHS: readonly string[];
export const CONVERSATION_PROMOTION_READINESS_GENERATED_OUTPUTS: readonly string[];
export function buildConversationPromotionReadinessReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V38_INFERENCE_SURFACE_INVENTORY_ARTIFACT_PATH: string;
export const V38_INFERENCE_SURFACE_INVENTORY_CURRENT_TARGET: string;
export const V38_INFERENCE_SURFACE_INVENTORY_SCHEMA_ID: string;
export const V38_INFERENCE_SURFACE_INVENTORY_VERSION: string;
export const V38_INFERENCE_SURFACE_INVENTORY_SOURCE_SAFETY_VERDICT: string;
export const V38_INFERENCE_SURFACE_REQUIRED_FAMILY_IDS: readonly string[];
export const V38_INFERENCE_SURFACE_REQUIRED_PRIMITIVE_IDS: readonly string[];
export const V38_INFERENCE_SURFACE_REQUIRED_READING_PIPELINE_NAMES: readonly string[];
export const V38_INFERENCE_SURFACE_DISCLOSURE_TIER_IDS: readonly string[];
export const V38_INFERENCE_SURFACE_ROWS: readonly Record<string, unknown>[];
export function buildV38InferenceSurfaceInventory(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V38_PTRR_FAILSAFE_THRICIFIED_STACK_ARTIFACT_PATH: string;
export const V38_PTRR_FAILSAFE_THRICIFIED_STACK_CURRENT_TARGET: string;
export const V38_PTRR_FAILSAFE_THRICIFIED_STACK_SCHEMA_ID: string;
export const V38_PTRR_FAILSAFE_THRICIFIED_STACK_VERSION: string;
export const V38_PTRR_FAILSAFE_THRICIFIED_STACK_SOURCE_SAFETY_VERDICT: string;
export const V38_PTRR_STEP_IDS: readonly string[];
export const V38_FAILSAFE_STAGE_IDS: readonly string[];
export const V38_THRICIFIED_GENERATION_STAGE_IDS: readonly string[];
export const V38_PTRR_FAILSAFE_THRICIFIED_STACK_ROWS: readonly Record<string, unknown>[];
export function buildV38PtrrFailsafeThricifiedStack(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V38_PROMPT_BENCHMARK_REPORT_ARTIFACT_PATH: string;
export const V38_PROMPT_BENCHMARK_REPORT_CURRENT_TARGET: string;
export const V38_PROMPT_BENCHMARK_REPORT_SCHEMA_ID: string;
export const V38_PROMPT_BENCHMARK_REPORT_VERSION: string;
export const V38_PROMPT_BENCHMARK_REPORT_SOURCE_SAFETY_VERDICT: string;
export const V38_PROMPT_BENCHMARK_SUBJECT_KIND_IDS: readonly string[];
export const V38_PROMPT_BENCHMARK_METRIC_IDS: readonly string[];
export const V38_PROMPT_BENCHMARK_DISCLOSURE_TIER_IDS: readonly string[];
export const V38_PROMPT_BENCHMARK_ROWS: readonly Record<string, unknown>[];
export function buildV38PromptBenchmarkReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V38_INFERENCE_TELEMETRY_DISCLOSURE_REPORT_ARTIFACT_PATH: string;
export const V38_INFERENCE_TELEMETRY_DISCLOSURE_REPORT_CURRENT_TARGET: string;
export const V38_INFERENCE_TELEMETRY_DISCLOSURE_REPORT_SCHEMA_ID: string;
export const V38_INFERENCE_TELEMETRY_DISCLOSURE_REPORT_VERSION: string;
export const V38_INFERENCE_TELEMETRY_DISCLOSURE_REPORT_SOURCE_SAFETY_VERDICT: string;
export const V38_INFERENCE_TELEMETRY_REQUIRED_LEVEL_IDS: readonly string[];
export const V38_INFERENCE_TELEMETRY_DISCLOSURE_TIER_IDS: readonly string[];
export const V38_INFERENCE_TELEMETRY_EVENT_KIND_IDS: readonly string[];
export const V38_INFERENCE_TELEMETRY_DISCLOSURE_ROWS: readonly Record<string, unknown>[];
export function buildV38InferenceTelemetryDisclosureReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V38_READ_NEED_COMPREHENSION_HARDENING_ARTIFACT_PATH: string;
export const V38_READ_NEED_COMPREHENSION_HARDENING_CURRENT_TARGET: string;
export const V38_READ_NEED_COMPREHENSION_HARDENING_SCHEMA_ID: string;
export const V38_READ_NEED_COMPREHENSION_HARDENING_VERSION: string;
export const V38_READ_NEED_COMPREHENSION_HARDENING_SOURCE_SAFETY_VERDICT: string;
export const V38_READ_NEED_COMPREHENSION_REQUIRED_PHASE_IDS: readonly string[];
export const V38_READ_NEED_COMPREHENSION_REQUIRED_RETURN_TYPES: readonly string[];
export const V38_READ_NEED_COMPREHENSION_REQUIRED_RECEIPT_FIELDS: readonly string[];
export const V38_READ_NEED_COMPREHENSION_HARDENING_ROWS: readonly Record<string, unknown>[];
export function buildV38ReadNeedComprehensionInferenceHardening(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V38_READ_FITS_FINDING_SEARCH_EMBEDDINGS_ARTIFACT_PATH: string;
export const V38_READ_FITS_FINDING_SEARCH_EMBEDDINGS_CURRENT_TARGET: string;
export const V38_READ_FITS_FINDING_SEARCH_EMBEDDINGS_SCHEMA_ID: string;
export const V38_READ_FITS_FINDING_SEARCH_EMBEDDINGS_VERSION: string;
export const V38_READ_FITS_FINDING_SEARCH_EMBEDDINGS_SOURCE_SAFETY_VERDICT: string;
export const V38_READ_FITS_FINDING_REQUIRED_PHASE_IDS: readonly string[];
export const V38_READ_FITS_FINDING_REQUIRED_RETURN_TYPES: readonly string[];
export const V38_READ_FITS_FINDING_SEARCH_CHANNEL_IDS: readonly string[];
export const V38_READ_FITS_FINDING_REQUIRED_RECEIPT_FIELDS: readonly string[];
export const V38_READ_FITS_FINDING_SEARCH_EMBEDDINGS_ROWS: readonly Record<string, unknown>[];
export function buildV38ReadFitsFindingSearchEmbeddings(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V38_ASSETPACK_SYNTHESIS_ECONOMIC_TRACEABILITY_ARTIFACT_PATH: string;
export const V38_ASSETPACK_SYNTHESIS_ECONOMIC_TRACEABILITY_CURRENT_TARGET: string;
export const V38_ASSETPACK_SYNTHESIS_ECONOMIC_TRACEABILITY_SCHEMA_ID: string;
export const V38_ASSETPACK_SYNTHESIS_ECONOMIC_TRACEABILITY_VERSION: string;
export const V38_ASSETPACK_SYNTHESIS_ECONOMIC_TRACEABILITY_SOURCE_SAFETY_VERDICT: string;
export const V38_ASSETPACK_SYNTHESIS_ECONOMIC_TRACEABILITY_ROW_IDS: readonly string[];
export const V38_ASSETPACK_SYNTHESIS_ECONOMIC_TRACEABILITY_REQUIRED_RECEIPT_FIELDS: readonly string[];
export const V38_ASSETPACK_SYNTHESIS_ECONOMIC_TRACEABILITY_ROWS: readonly Record<string, unknown>[];
export function buildV38AssetPackSynthesisEconomicTraceability(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V38_CONVERSATION_TOOL_PROMPT_INFERENCE_PARITY_ARTIFACT_PATH: string;
export const V38_CONVERSATION_TOOL_PROMPT_INFERENCE_PARITY_CURRENT_TARGET: string;
export const V38_CONVERSATION_TOOL_PROMPT_INFERENCE_PARITY_SCHEMA_ID: string;
export const V38_CONVERSATION_TOOL_PROMPT_INFERENCE_PARITY_VERSION: string;
export const V38_CONVERSATION_TOOL_PROMPT_INFERENCE_PARITY_SOURCE_SAFETY_VERDICT: string;
export const V38_CONVERSATION_TOOL_PROMPT_INFERENCE_PARITY_ROW_IDS: readonly string[];
export const V38_CONVERSATION_TOOL_PROMPT_INFERENCE_PARITY_REQUIRED_DISCLOSURE_POSTURES: readonly string[];
export const V38_CONVERSATION_TOOL_PROMPT_INFERENCE_PARITY_ROWS: readonly Record<string, unknown>[];
export function buildV38ConversationToolPromptInferenceParity(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V38_LOCAL_STAGING_INFERENCE_DEPOSITORY_SEARCH_REHEARSAL_ARTIFACT_PATH: string;
export const V38_LOCAL_STAGING_INFERENCE_DEPOSITORY_SEARCH_REHEARSAL_CURRENT_TARGET: string;
export const V38_LOCAL_STAGING_INFERENCE_DEPOSITORY_SEARCH_REHEARSAL_SCHEMA_ID: string;
export const V38_LOCAL_STAGING_INFERENCE_DEPOSITORY_SEARCH_REHEARSAL_VERSION: string;
export const V38_LOCAL_STAGING_INFERENCE_DEPOSITORY_SEARCH_REHEARSAL_SOURCE_SAFETY_VERDICT: string;
export const V38_LOCAL_STAGING_INFERENCE_DEPOSITORY_SEARCH_REHEARSAL_ROW_IDS: readonly string[];
export const V38_LOCAL_STAGING_INFERENCE_DEPOSITORY_SEARCH_REHEARSAL_LANE_IDS: readonly string[];
export const V38_LOCAL_STAGING_INFERENCE_DEPOSITORY_SEARCH_REHEARSAL_REQUIRED_PROOF_ARTIFACTS: readonly string[];
export const V38_LOCAL_STAGING_INFERENCE_DEPOSITORY_SEARCH_REHEARSAL_ROWS: readonly Record<string, unknown>[];
export function buildV38LocalStagingInferenceDepositorySearchRehearsal(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V38_INFERENCE_PROMOTION_READINESS_REPORT_ARTIFACT_PATH: string;
export const V38_INFERENCE_PROMOTION_READINESS_REPORT_CURRENT_TARGET: string;
export const V38_INFERENCE_PROMOTION_READINESS_REPORT_SCHEMA_ID: string;
export const V38_INFERENCE_PROMOTION_READINESS_REPORT_VERSION: string;
export const V38_INFERENCE_PROMOTION_READINESS_SOURCE_SAFETY_VERDICT: string;
export const V38_INFERENCE_PROMOTION_READINESS_GATE_ARTIFACT_PATHS: readonly string[];
export const V38_INFERENCE_PROMOTION_READINESS_GENERATED_OUTPUTS: readonly string[];
export function buildV38InferencePromotionReadinessReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V39_DEPOSITORY_SUPPLY_INDEXING_ARTIFACT_PATH: string;
export const V39_DEPOSITORY_SUPPLY_INDEXING_CURRENT_TARGET: string;
export const V39_DEPOSITORY_SUPPLY_INDEXING_SCHEMA_ID: string;
export const V39_DEPOSITORY_SUPPLY_INDEXING_VERSION: string;
export const V39_DEPOSITORY_SUPPLY_INDEXING_SOURCE_SAFETY_VERDICT: string;
export const V39_DEPOSITORY_SUPPLY_INDEXING_ROW_IDS: readonly string[];
export const V39_DEPOSITORY_SUPPLY_INDEXING_ROWS: readonly Record<string, unknown>[];
export function buildV39DepositorySupplyIndexing(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V39_ENTERPRISE_READING_UX_STATE_ARTIFACT_PATH: string;
export const V39_ENTERPRISE_READING_UX_STATE_CURRENT_TARGET: string;
export const V39_ENTERPRISE_READING_UX_STATE_SCHEMA_ID: string;
export const V39_ENTERPRISE_READING_UX_STATE_VERSION: string;
export const V39_ENTERPRISE_READING_UX_STATE_SOURCE_SAFETY_VERDICT: string;
export const V39_ENTERPRISE_READING_STEP_IDS: readonly string[];
export const V39_ENTERPRISE_READING_UX_ROW_IDS: readonly string[];
export const V39_ENTERPRISE_READING_UX_ROWS: readonly Record<string, unknown>[];
export function buildV39EnterpriseReadingUxState(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V39_READ_NEED_REVIEW_RESYNTHESIS_ARTIFACT_PATH: string;
export const V39_READ_NEED_REVIEW_RESYNTHESIS_CURRENT_TARGET: string;
export const V39_READ_NEED_REVIEW_RESYNTHESIS_SCHEMA_ID: string;
export const V39_READ_NEED_REVIEW_RESYNTHESIS_VERSION: string;
export const V39_READ_NEED_REVIEW_RESYNTHESIS_SOURCE_SAFETY_VERDICT: string;
export const V39_READ_NEED_REVIEW_RESYNTHESIS_ROW_IDS: readonly string[];
export const V39_READ_NEED_REVIEW_RESYNTHESIS_ROWS: readonly Record<string, unknown>[];
export function buildV39ReadNeedReviewResynthesis(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V39_READ_FITS_FINDING_RUNTIME_ARTIFACT_PATH: string;
export const V39_READ_FITS_FINDING_RUNTIME_CURRENT_TARGET: string;
export const V39_READ_FITS_FINDING_RUNTIME_SCHEMA_ID: string;
export const V39_READ_FITS_FINDING_RUNTIME_VERSION: string;
export const V39_READ_FITS_FINDING_RUNTIME_SOURCE_SAFETY_VERDICT: string;
export const V39_READ_FITS_FINDING_RUNTIME_ROW_IDS: readonly string[];
export const V39_READ_FITS_FINDING_RUNTIME_ROWS: readonly Record<string, unknown>[];
export function buildV39ReadFitsFindingRuntime(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V39_ASSETPACK_PREVIEW_QUOTE_BOUNDARY_ARTIFACT_PATH: string;
export const V39_ASSETPACK_PREVIEW_QUOTE_BOUNDARY_CURRENT_TARGET: string;
export const V39_ASSETPACK_PREVIEW_QUOTE_BOUNDARY_SCHEMA_ID: string;
export const V39_ASSETPACK_PREVIEW_QUOTE_BOUNDARY_VERSION: string;
export const V39_ASSETPACK_PREVIEW_QUOTE_BOUNDARY_SOURCE_SAFETY_VERDICT: string;
export const V39_ASSETPACK_PREVIEW_QUOTE_BOUNDARY_ROW_IDS: readonly string[];
export const V39_ASSETPACK_PREVIEW_QUOTE_BOUNDARY_ROWS: readonly Record<string, unknown>[];
export function buildV39AssetPackPreviewQuoteBoundary(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V39_SETTLEMENT_RIGHTS_DELIVERY_ARTIFACT_PATH: string;
export const V39_SETTLEMENT_RIGHTS_DELIVERY_CURRENT_TARGET: string;
export const V39_SETTLEMENT_RIGHTS_DELIVERY_SCHEMA_ID: string;
export const V39_SETTLEMENT_RIGHTS_DELIVERY_VERSION: string;
export const V39_SETTLEMENT_RIGHTS_DELIVERY_SOURCE_SAFETY_VERDICT: string;
export const V39_SETTLEMENT_RIGHTS_DELIVERY_ROW_IDS: readonly string[];
export const V39_SETTLEMENT_RIGHTS_DELIVERY_ROWS: readonly Record<string, unknown>[];
export function buildV39SettlementRightsDelivery(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V39_OPERATIONAL_TELEMETRY_REPAIR_READBACK_ARTIFACT_PATH: string;
export const V39_OPERATIONAL_TELEMETRY_REPAIR_READBACK_CURRENT_TARGET: string;
export const V39_OPERATIONAL_TELEMETRY_REPAIR_READBACK_SCHEMA_ID: string;
export const V39_OPERATIONAL_TELEMETRY_REPAIR_READBACK_VERSION: string;
export const V39_OPERATIONAL_TELEMETRY_REPAIR_READBACK_SOURCE_SAFETY_VERDICT: string;
export const V39_OPERATIONAL_TELEMETRY_EVENT_KIND_IDS: readonly string[];
export const V39_OPERATIONAL_TELEMETRY_REPAIR_READBACK_ROW_IDS: readonly string[];
export const V39_OPERATIONAL_TELEMETRY_REPAIR_READBACK_ROWS: readonly Record<string, unknown>[];
export function buildV39OperationalTelemetryRepairReadback(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V39_INTERFACE_CONVERSATION_PRODUCT_PARITY_ARTIFACT_PATH: string;
export const V39_INTERFACE_CONVERSATION_PRODUCT_PARITY_CURRENT_TARGET: string;
export const V39_INTERFACE_CONVERSATION_PRODUCT_PARITY_SCHEMA_ID: string;
export const V39_INTERFACE_CONVERSATION_PRODUCT_PARITY_VERSION: string;
export const V39_INTERFACE_CONVERSATION_PRODUCT_PARITY_SOURCE_SAFETY_VERDICT: string;
export const V39_INTERFACE_CONVERSATION_PRODUCT_PARITY_SURFACES: readonly string[];
export const V39_INTERFACE_CONVERSATION_PRODUCT_PARITY_STAGE_IDS: readonly string[];
export const V39_INTERFACE_CONVERSATION_PRODUCT_PARITY_ROW_IDS: readonly string[];
export const V39_INTERFACE_CONVERSATION_PRODUCT_PARITY_ROWS: readonly Record<string, unknown>[];
export function buildV39InterfaceConversationProductParity(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V39_LOCAL_STAGING_READING_REHEARSAL_ARTIFACT_PATH: string;
export const V39_LOCAL_STAGING_READING_REHEARSAL_CURRENT_TARGET: string;
export const V39_LOCAL_STAGING_READING_REHEARSAL_SCHEMA_ID: string;
export const V39_LOCAL_STAGING_READING_REHEARSAL_VERSION: string;
export const V39_LOCAL_STAGING_READING_REHEARSAL_SOURCE_SAFETY_VERDICT: string;
export const V39_LOCAL_STAGING_READING_REHEARSAL_LANE_IDS: readonly string[];
export const V39_LOCAL_STAGING_READING_REHEARSAL_STAGE_IDS: readonly string[];
export const V39_LOCAL_STAGING_READING_REHEARSAL_ROW_IDS: readonly string[];
export const V39_LOCAL_STAGING_READING_REHEARSAL_ROWS: readonly Record<string, unknown>[];
export function buildV39LocalStagingReadingRehearsal(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V39_COMMERCIAL_READING_PROMOTION_READINESS_REPORT_ARTIFACT_PATH: string;
export const V39_COMMERCIAL_READING_PROMOTION_READINESS_REPORT_CURRENT_TARGET: string;
export const V39_COMMERCIAL_READING_PROMOTION_READINESS_REPORT_SCHEMA_ID: string;
export const V39_COMMERCIAL_READING_PROMOTION_READINESS_REPORT_VERSION: string;
export const V39_COMMERCIAL_READING_PROMOTION_READINESS_SOURCE_SAFETY_VERDICT: string;
export const V39_COMMERCIAL_READING_PROMOTION_READINESS_GATE_ARTIFACT_PATHS: readonly string[];
export const V39_COMMERCIAL_READING_PROMOTION_READINESS_GENERATED_OUTPUTS: readonly string[];
export function buildV39CommercialReadingPromotionReadinessReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V40_TEST_INVENTORY_COVERAGE_MATRIX_ARTIFACT_PATH: string;
export const V40_TEST_INVENTORY_COVERAGE_MATRIX_CURRENT_TARGET: string;
export const V40_TEST_INVENTORY_COVERAGE_MATRIX_SCHEMA_ID: string;
export const V40_TEST_INVENTORY_COVERAGE_MATRIX_VERSION: string;
export const V40_TEST_INVENTORY_COVERAGE_MATRIX_SOURCE_SAFETY_VERDICT: string;
export const V40_TEST_INVENTORY_SURFACE_IDS: readonly string[];
export const V40_TEST_INVENTORY_COVERAGE_TIERS: readonly string[];
export const V40_TEST_INVENTORY_COVERAGE_ROWS: readonly Record<string, unknown>[];
export function buildV40TestInventoryCoverageMatrix(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V40_UNIT_COVERAGE_INVENTORY_ARTIFACT_PATH: string;
export const V40_UNIT_COVERAGE_INVENTORY_CURRENT_TARGET: string;
export const V40_UNIT_COVERAGE_INVENTORY_SCHEMA_ID: string;
export const V40_UNIT_COVERAGE_INVENTORY_VERSION: string;
export const V40_UNIT_COVERAGE_INVENTORY_SOURCE_SAFETY_VERDICT: string;
export const V40_UNIT_COVERAGE_SURFACE_IDS: readonly string[];
export const V40_UNIT_COVERAGE_VERDICTS: readonly string[];
export const V40_UNIT_COVERAGE_ROWS: readonly Record<string, unknown>[];
export function buildV40UnitCoverageInventory(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V40_API_INTEGRATION_CONTRACTS_ARTIFACT_PATH: string;
export const V40_API_INTEGRATION_CONTRACTS_CURRENT_TARGET: string;
export const V40_API_INTEGRATION_CONTRACTS_SCHEMA_ID: string;
export const V40_API_INTEGRATION_CONTRACTS_VERSION: string;
export const V40_API_INTEGRATION_CONTRACTS_SOURCE_SAFETY_VERDICT: string;
export const V40_API_INTEGRATION_SURFACE_IDS: readonly string[];
export const V40_API_INTEGRATION_VERDICTS: readonly string[];
export const V40_API_INTEGRATION_CONTRACT_ROWS: readonly Record<string, unknown>[];
export function buildV40ApiIntegrationContracts(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V40_READING_PIPELINE_INTEGRATION_COVERAGE_ARTIFACT_PATH: string;
export const V40_READING_PIPELINE_INTEGRATION_COVERAGE_CURRENT_TARGET: string;
export const V40_READING_PIPELINE_INTEGRATION_COVERAGE_SCHEMA_ID: string;
export const V40_READING_PIPELINE_INTEGRATION_COVERAGE_VERSION: string;
export const V40_READING_PIPELINE_INTEGRATION_COVERAGE_SOURCE_SAFETY_VERDICT: string;
export const V40_READING_PIPELINE_NAMES: readonly string[];
export const V40_READING_PIPELINE_INTEGRATION_SURFACE_IDS: readonly string[];
export const V40_READING_PIPELINE_INTEGRATION_VERDICTS: readonly string[];
export const V40_READING_PIPELINE_EXPECTED_TOTALS: Readonly<Record<string, number>>;
export const V40_READING_PIPELINE_INTEGRATION_ROWS: readonly Record<string, unknown>[];
export function buildV40ReadingPipelineIntegrationCoverage(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V40_CONVERSATION_TERMINAL_INTEGRATION_ARTIFACT_PATH: string;
export const V40_CONVERSATION_TERMINAL_INTEGRATION_CURRENT_TARGET: string;
export const V40_CONVERSATION_TERMINAL_INTEGRATION_SCHEMA_ID: string;
export const V40_CONVERSATION_TERMINAL_INTEGRATION_VERSION: string;
export const V40_CONVERSATION_TERMINAL_INTEGRATION_SOURCE_SAFETY_VERDICT: string;
export const V40_CONVERSATION_TERMINAL_SURFACE_IDS: readonly string[];
export const V40_CONVERSATION_TERMINAL_VERDICTS: readonly string[];
export const V40_CONVERSATION_TERMINAL_EXPECTED_TOTALS: Readonly<Record<string, number>>;
export const V40_CONVERSATION_TERMINAL_INTEGRATION_ROWS: readonly Record<string, unknown>[];
export function buildV40ConversationTerminalIntegration(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V40_BROWSER_E2E_VISUAL_PROOF_ARTIFACT_PATH: string;
export const V40_BROWSER_E2E_VISUAL_PROOF_CURRENT_TARGET: string;
export const V40_BROWSER_E2E_VISUAL_PROOF_SCHEMA_ID: string;
export const V40_BROWSER_E2E_VISUAL_PROOF_VERSION: string;
export const V40_BROWSER_E2E_VISUAL_PROOF_SOURCE_SAFETY_VERDICT: string;
export const V40_BROWSER_E2E_VISUAL_SURFACE_IDS: readonly string[];
export const V40_BROWSER_E2E_VISUAL_VERDICTS: readonly string[];
export const V40_BROWSER_E2E_VISUAL_EXPECTED_TOTALS: Readonly<Record<string, number>>;
export const V40_BROWSER_E2E_VISUAL_ROWS: readonly Record<string, unknown>[];
export function buildV40BrowserE2eVisualProof(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V40_LEDGER_STORAGE_SYNC_ARTIFACT_PATH: string;
export const V40_LEDGER_STORAGE_SYNC_CURRENT_TARGET: string;
export const V40_LEDGER_STORAGE_SYNC_SCHEMA_ID: string;
export const V40_LEDGER_STORAGE_SYNC_VERSION: string;
export const V40_LEDGER_STORAGE_SYNC_SOURCE_SAFETY_VERDICT: string;
export const V40_LEDGER_STORAGE_SYNC_ROW_IDS: readonly string[];
export const V40_LEDGER_STORAGE_SYNC_VERDICTS: readonly string[];
export const V40_LEDGER_STORAGE_SYNC_EXPECTED_TOTALS: Readonly<Record<string, number>>;
export const V40_LEDGER_STORAGE_SYNC_ROWS: readonly Record<string, unknown>[];
export function buildV40LedgerStorageSync(input?: Record<string, unknown>): BitcodeProtocolReport;
export function listMissingV40LedgerStorageSyncSources(repoRoot?: string): string[];
export const V40_LOCAL_STAGING_REHEARSAL_AUTOMATION_ARTIFACT_PATH: string;
export const V40_LOCAL_STAGING_REHEARSAL_AUTOMATION_CURRENT_TARGET: string;
export const V40_LOCAL_STAGING_REHEARSAL_AUTOMATION_SCHEMA_ID: string;
export const V40_LOCAL_STAGING_REHEARSAL_AUTOMATION_VERSION: string;
export const V40_LOCAL_STAGING_REHEARSAL_AUTOMATION_SOURCE_SAFETY_VERDICT: string;
export const V40_LOCAL_STAGING_REHEARSAL_AUTOMATION_LANE_IDS: readonly string[];
export const V40_LOCAL_STAGING_REHEARSAL_AUTOMATION_ROW_IDS: readonly string[];
export const V40_LOCAL_STAGING_REHEARSAL_AUTOMATION_EXPECTED_TOTALS: Readonly<Record<string, number>>;
export const V40_LOCAL_STAGING_REHEARSAL_AUTOMATION_ROWS: readonly Record<string, unknown>[];
export function buildV40LocalStagingRehearsalAutomation(input?: Record<string, unknown>): BitcodeProtocolReport;
export function listMissingV40LocalStagingRehearsalAutomationSources(repoRoot?: string): string[];
export const V40_PROMPT_BENCHMARK_SMOKE_V41_READINESS_ARTIFACT_PATH: string;
export const V40_PROMPT_BENCHMARK_SMOKE_V41_READINESS_CURRENT_TARGET: string;
export const V40_PROMPT_BENCHMARK_SMOKE_V41_READINESS_SCHEMA_ID: string;
export const V40_PROMPT_BENCHMARK_SMOKE_V41_READINESS_VERSION: string;
export const V40_PROMPT_BENCHMARK_SMOKE_V41_READINESS_SOURCE_SAFETY_VERDICT: string;
export const V40_PROMPT_BENCHMARK_SMOKE_ROW_IDS: readonly string[];
export const V40_PROMPT_BENCHMARK_SMOKE_EXPECTED_TOTALS: Readonly<Record<string, number>>;
export const V40_PROMPT_BENCHMARK_SMOKE_COMMAND_IDS: readonly string[];
export const V40_PROMPT_BENCHMARK_SMOKE_V41_WORK_ITEM_IDS: readonly string[];
export const V40_PROMPT_BENCHMARK_SMOKE_ROWS: readonly Record<string, unknown>[];
export function buildV40PromptBenchmarkSmokeV41Readiness(input?: Record<string, unknown>): BitcodeProtocolReport;
export function listMissingV40PromptBenchmarkSmokeV41ReadinessSources(repoRoot?: string): string[];
export const V40_PROMOTION_READINESS_REPORT_ARTIFACT_PATH: string;
export const V40_PROMOTION_READINESS_REPORT_CURRENT_TARGET: string;
export const V40_PROMOTION_READINESS_REPORT_SCHEMA_ID: string;
export const V40_PROMOTION_READINESS_REPORT_VERSION: string;
export const V40_PROMOTION_READINESS_SOURCE_SAFETY_VERDICT: string;
export const V40_PROMOTION_READINESS_GATE_ARTIFACT_PATHS: readonly string[];
export const V40_PROMOTION_READINESS_GENERATED_OUTPUTS: readonly string[];
export function buildV40PromotionReadinessReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export function listMissingV40PromotionReadinessSources(repoRoot?: string): string[];
export const V41_PROMPTPART_PROMPT_INVENTORY_ARTIFACT_PATH: string;
export const V41_PROMPTPART_PROMPT_INVENTORY_CURRENT_TARGET: string;
export const V41_PROMPTPART_PROMPT_INVENTORY_SCHEMA_ID: string;
export const V41_PROMPTPART_PROMPT_INVENTORY_VERSION: string;
export const V41_PROMPTPART_PROMPT_INVENTORY_SOURCE_SAFETY_VERDICT: string;
export const V41_PROMPT_INVENTORY_REQUIRED_SURFACE_IDS: readonly string[];
export const V41_PROMPT_INVENTORY_REQUIRED_FIELD_IDS: readonly string[];
export const V41_PROMPT_INVENTORY_DISCLOSURE_TIERS: readonly string[];
export function buildV41PromptPartPromptInventory(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V41_REGISTRY_INTERPOLATION_CONTRACTS_ARTIFACT_PATH: string;
export const V41_REGISTRY_INTERPOLATION_CONTRACTS_CURRENT_TARGET: string;
export const V41_REGISTRY_INTERPOLATION_CONTRACTS_SCHEMA_ID: string;
export const V41_REGISTRY_INTERPOLATION_CONTRACTS_VERSION: string;
export const V41_REGISTRY_INTERPOLATION_CONTRACTS_SOURCE_SAFETY_VERDICT: string;
export const V41_REGISTRY_INTERPOLATION_REQUIRED_FIELD_IDS: readonly string[];
export const V41_REGISTRY_INTERPOLATION_COMPOSITION_LEVEL_IDS: readonly string[];
export const V41_REGISTRY_INTERPOLATION_DISCLOSURE_TIERS: readonly string[];
export const V41_REGISTRY_INTERPOLATION_CONTRACT_ROWS: readonly Record<string, unknown>[];
export function buildV41RegistryInterpolationContracts(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V41_READING_PROMPT_BENCHMARK_BASELINES_ARTIFACT_PATH: string;
export const V41_READING_PROMPT_BENCHMARK_BASELINES_CURRENT_TARGET: string;
export const V41_READING_PROMPT_BENCHMARK_BASELINES_SCHEMA_ID: string;
export const V41_READING_PROMPT_BENCHMARK_BASELINES_VERSION: string;
export const V41_READING_PROMPT_BENCHMARK_BASELINES_SOURCE_SAFETY_VERDICT: string;
export const V41_READING_PROMPT_BENCHMARK_PIPELINE_IDS: readonly string[];
export const V41_READING_PROMPT_BENCHMARK_METRIC_IDS: readonly string[];
export const V41_READING_PROMPT_BENCHMARK_DISCLOSURE_TIERS: readonly string[];
export const V41_READING_PROMPT_BENCHMARK_BASELINE_ROWS: readonly Record<string, unknown>[];
export function buildV41ReadingPromptBenchmarkBaselines(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V41_READNEED_PROMPT_HARDENING_ARTIFACT_PATH: string;
export const V41_READNEED_PROMPT_HARDENING_CURRENT_TARGET: string;
export const V41_READNEED_PROMPT_HARDENING_SCHEMA_ID: string;
export const V41_READNEED_PROMPT_HARDENING_VERSION: string;
export const V41_READNEED_PROMPT_HARDENING_SOURCE_SAFETY_VERDICT: string;
export const V41_READNEED_PROMPT_HARDENING_METRIC_IDS: readonly string[];
export const V41_READNEED_PROMPT_HARDENING_DISCLOSURE_TIERS: readonly string[];
export const V41_READNEED_PROMPT_HARDENING_ROWS: readonly Record<string, unknown>[];
export function buildV41ReadNeedPromptHardening(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V41_READFITSFINDING_PROMPT_HARDENING_ARTIFACT_PATH: string;
export const V41_READFITSFINDING_PROMPT_HARDENING_CURRENT_TARGET: string;
export const V41_READFITSFINDING_PROMPT_HARDENING_SCHEMA_ID: string;
export const V41_READFITSFINDING_PROMPT_HARDENING_VERSION: string;
export const V41_READFITSFINDING_PROMPT_HARDENING_SOURCE_SAFETY_VERDICT: string;
export const V41_READFITSFINDING_PROMPT_HARDENING_METRIC_IDS: readonly string[];
export const V41_READFITSFINDING_PROMPT_HARDENING_DISCLOSURE_TIERS: readonly string[];
export const V41_READFITSFINDING_PROMPT_HARDENING_ROWS: readonly Record<string, unknown>[];
export function buildV41ReadFitsFindingPromptHardening(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V41_CONVERSATION_TOOL_INTERFACE_PROMPT_REWRITE_ARTIFACT_PATH: string;
export const V41_CONVERSATION_TOOL_INTERFACE_PROMPT_REWRITE_CURRENT_TARGET: string;
export const V41_CONVERSATION_TOOL_INTERFACE_PROMPT_REWRITE_SCHEMA_ID: string;
export const V41_CONVERSATION_TOOL_INTERFACE_PROMPT_REWRITE_VERSION: string;
export const V41_CONVERSATION_TOOL_INTERFACE_PROMPT_REWRITE_SOURCE_SAFETY_VERDICT: string;
export const V41_CONVERSATION_TOOL_INTERFACE_PROMPT_REWRITE_METRIC_IDS: readonly string[];
export const V41_CONVERSATION_TOOL_INTERFACE_PROMPT_REWRITE_DISCLOSURE_TIERS: readonly string[];
export const V41_CONVERSATION_TOOL_INTERFACE_PROMPT_REWRITE_ROWS: readonly Record<string, unknown>[];
export function buildV41ConversationToolInterfacePromptRewrite(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V41_PROMPT_PROGRAM_BENCHMARK_REPORT_ARTIFACT_PATH: string;
export const V41_PROMPT_PROGRAM_BENCHMARK_REPORT_CURRENT_TARGET: string;
export const V41_PROMPT_PROGRAM_BENCHMARK_REPORT_SCHEMA_ID: string;
export const V41_PROMPT_PROGRAM_BENCHMARK_REPORT_VERSION: string;
export const V41_PROMPT_PROGRAM_BENCHMARK_REPORT_SOURCE_SAFETY_VERDICT: string;
export const V41_PROMPT_PROGRAM_BENCHMARK_REPORT_METRIC_IDS: readonly string[];
export const V41_PROMPT_PROGRAM_BENCHMARK_REPORT_DISCLOSURE_TIERS: readonly string[];
export const V41_PROMPT_PROGRAM_BENCHMARK_REPORT_ROWS: readonly Record<string, unknown>[];
export function buildV41PromptProgramBenchmarkReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V41_PROMOTION_READINESS_REPORT_ARTIFACT_PATH: string;
export const V41_PROMOTION_READINESS_REPORT_CURRENT_TARGET: string;
export const V41_PROMOTION_READINESS_REPORT_SCHEMA_ID: string;
export const V41_PROMOTION_READINESS_REPORT_VERSION: string;
export const V41_PROMOTION_READINESS_SOURCE_SAFETY_VERDICT: string;
export const V41_PROMOTION_READINESS_GATE_ARTIFACT_PATHS: readonly string[];
export const V41_PROMOTION_READINESS_GENERATED_OUTPUTS: readonly string[];
export function buildV41PromotionReadinessReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export function listMissingV41PromotionReadinessSources(repoRoot?: string): string[];
export const V42_DEPOSITING_SHORTEST_PATH_ARTIFACT_PATH: string;
export const V42_DEPOSITING_SHORTEST_PATH_CURRENT_TARGET: string;
export const V42_DEPOSITING_SHORTEST_PATH_SCHEMA_ID: string;
export const V42_DEPOSITING_SHORTEST_PATH_VERSION: string;
export const V42_DEPOSITING_SHORTEST_PATH_SOURCE_SAFETY_VERDICT: string;
export const V42_DEPOSITING_SHORTEST_PATH_ROW_IDS: readonly string[];
export const V42_DEPOSITING_SHORTEST_PATH_ROWS: readonly Record<string, unknown>[];
export function buildV42DepositingShortestPath(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V42_READING_SHORTEST_PATH_STATE_MACHINE_ARTIFACT_PATH: string;
export const V42_READING_SHORTEST_PATH_STATE_MACHINE_CURRENT_TARGET: string;
export const V42_READING_SHORTEST_PATH_SCHEMA_ID: string;
export const V42_READING_SHORTEST_PATH_STATE_MACHINE_VERSION: string;
export const V42_READING_SHORTEST_PATH_STATE_MACHINE_SOURCE_SAFETY_VERDICT: string;
export const V42_READING_SHORTEST_PATH_STEP_IDS: readonly string[];
export const V42_READING_SHORTEST_PATH_ROW_IDS: readonly string[];
export const V42_READING_SHORTEST_PATH_ROWS: readonly Record<string, unknown>[];
export function buildV42ReadingShortestPathStateMachine(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V42_READNEED_REVIEW_RESYNTHESIS_PRODUCT_CLOSURE_ARTIFACT_PATH: string;
export const V42_READNEED_REVIEW_RESYNTHESIS_PRODUCT_CLOSURE_CURRENT_TARGET: string;
export const V42_READNEED_REVIEW_RESYNTHESIS_PRODUCT_CLOSURE_SCHEMA_ID: string;
export const V42_READNEED_REVIEW_RESYNTHESIS_SCHEMA_ID: string;
export const V42_READNEED_REVIEW_RESYNTHESIS_PRODUCT_CLOSURE_VERSION: string;
export const V42_READNEED_REVIEW_RESYNTHESIS_PRODUCT_CLOSURE_SOURCE_SAFETY_VERDICT: string;
export const V42_READNEED_REVIEW_RESYNTHESIS_PRODUCT_CLOSURE_ROW_IDS: readonly string[];
export const V42_READNEED_REVIEW_RESYNTHESIS_PRODUCT_CLOSURE_ROWS: readonly Record<string, unknown>[];
export function buildV42ReadNeedReviewResynthesisProductClosure(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V42_READFITSFINDING_PREVIEW_QUOTE_ARTIFACT_PATH: string;
export const V42_READFITSFINDING_PREVIEW_QUOTE_CURRENT_TARGET: string;
export const V42_READFITSFINDING_PREVIEW_QUOTE_SCHEMA_ID: string;
export const V42_READFITSFINDING_PREVIEW_QUOTE_VERSION: string;
export const V42_READFITSFINDING_PREVIEW_QUOTE_SOURCE_SAFETY_VERDICT: string;
export const V42_READFITSFINDING_PREVIEW_QUOTE_ROW_IDS: readonly string[];
export const V42_READFITSFINDING_PREVIEW_QUOTE_ROWS: readonly Record<string, unknown>[];
export function buildV42ReadFitsFindingPreviewQuote(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V42_SETTLEMENT_RIGHTS_DELIVERY_ARTIFACT_PATH: string;
export const V42_SETTLEMENT_RIGHTS_DELIVERY_CURRENT_TARGET: string;
export const V42_SETTLEMENT_RIGHTS_DELIVERY_SCHEMA_ID: string;
export const V42_SETTLEMENT_RIGHTS_DELIVERY_VERSION: string;
export const V42_SETTLEMENT_RIGHTS_DELIVERY_SOURCE_SAFETY_VERDICT: string;
export const V42_SETTLEMENT_RIGHTS_DELIVERY_ROW_IDS: readonly string[];
export const V42_SETTLEMENT_RIGHTS_DELIVERY_ROWS: readonly Record<string, unknown>[];
export function buildV42SettlementRightsDelivery(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V42_AI_READING_DEMONSTRATION_ARTIFACT_PATH: string;
export const V42_AI_READING_DEMONSTRATION_CURRENT_TARGET: string;
export const V42_AI_READING_DEMONSTRATION_SCHEMA_ID: string;
export const V42_AI_READING_DEMONSTRATION_VERSION: string;
export const V42_AI_READING_DEMONSTRATION_SOURCE_SAFETY_VERDICT: string;
export const V42_AI_READING_DEMONSTRATION_ROW_IDS: readonly string[];
export const V42_AI_READING_DEMONSTRATION_ROWS: readonly Record<string, unknown>[];
export function buildV42AiReadingDemonstration(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V42_LOCAL_STAGING_MVP_REHEARSAL_ARTIFACT_PATH: string;
export const V42_LOCAL_STAGING_MVP_REHEARSAL_CURRENT_TARGET: string;
export const V42_LOCAL_STAGING_MVP_REHEARSAL_SCHEMA_ID: string;
export const V42_LOCAL_STAGING_MVP_REHEARSAL_VERSION: string;
export const V42_LOCAL_STAGING_MVP_REHEARSAL_SOURCE_SAFETY_VERDICT: string;
export const V42_LOCAL_STAGING_MVP_REHEARSAL_LANE_IDS: readonly string[];
export const V42_LOCAL_STAGING_MVP_REHEARSAL_STAGE_IDS: readonly string[];
export const V42_LOCAL_STAGING_MVP_REHEARSAL_ROW_IDS: readonly string[];
export const V42_LOCAL_STAGING_MVP_REHEARSAL_ROWS: readonly Record<string, unknown>[];
export function buildV42LocalStagingMvpRehearsal(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V42_PROMOTION_READINESS_REPORT_ARTIFACT_PATH: string;
export const V42_PROMOTION_READINESS_REPORT_CURRENT_TARGET: string;
export const V42_PROMOTION_READINESS_REPORT_SCHEMA_ID: string;
export const V42_PROMOTION_READINESS_REPORT_VERSION: string;
export const V42_PROMOTION_READINESS_SOURCE_SAFETY_VERDICT: string;
export const V42_PROMOTION_READINESS_GATE_ARTIFACT_PATHS: readonly string[];
export const V42_PROMOTION_READINESS_GENERATED_OUTPUTS: readonly string[];
export function buildV42PromotionReadinessReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export function listMissingV42PromotionReadinessSources(repoRoot?: string): string[];
export const V43_ROUTE_VOCABULARY_INVENTORY_ARTIFACT_PATH: string;
export const V43_ROUTE_VOCABULARY_INVENTORY_CURRENT_TARGET: string;
export const V43_ROUTE_VOCABULARY_INVENTORY_SCHEMA_ID: string;
export const V43_ROUTE_VOCABULARY_INVENTORY_VERSION: string;
export const V43_ROUTE_VOCABULARY_INVENTORY_SOURCE_SAFETY_VERDICT: string;
export const V43_ROUTE_VOCABULARY_TOKEN_IDS: readonly string[];
export const V43_ROUTE_VOCABULARY_CATEGORY_IDS: readonly string[];
export const V43_ROUTE_VOCABULARY_MIGRATION_ROW_IDS: readonly string[];
export const V43_ROUTE_VOCABULARY_MIGRATION_ROWS: readonly Record<string, unknown>[];
export function buildV43RouteVocabularyInventory(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V43_PACKS_ACTIVITY_MASTER_DETAIL_ARTIFACT_PATH: string;
export const V43_PACKS_ACTIVITY_MASTER_DETAIL_CURRENT_TARGET: string;
export const V43_PACKS_ACTIVITY_MASTER_DETAIL_SCHEMA_ID: string;
export const V43_PACKS_ACTIVITY_MASTER_DETAIL_VERSION: string;
export const V43_PACKS_ACTIVITY_MASTER_DETAIL_SOURCE_SAFETY_VERDICT: string;
export const V43_PACKS_ACTIVITY_MASTER_DETAIL_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V43_PACK_ACTIVITY_TYPE_IDS: readonly string[];
export const V43_PACK_ACTIVITY_SEARCH_FIELD_IDS: readonly string[];
export const V43_PACK_ACTIVITY_SORT_IDS: readonly string[];
export const V43_PACK_ACTIVITY_FILTER_IDS: readonly string[];
export const V43_PACK_ACTIVITY_DETAIL_SECTION_IDS: readonly string[];
export const V43_PACK_ACTIVITY_CONTRACT_ROWS: readonly Record<string, unknown>[];
export function buildV43PacksActivityMasterDetail(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V43_READ_ROUTE_FIVE_STEP_UX_ARTIFACT_PATH: string;
export const V43_READ_ROUTE_FIVE_STEP_UX_CURRENT_TARGET: string;
export const V43_READ_ROUTE_FIVE_STEP_UX_SCHEMA_ID: string;
export const V43_READ_ROUTE_FIVE_STEP_UX_VERSION: string;
export const V43_READ_ROUTE_FIVE_STEP_UX_SOURCE_SAFETY_VERDICT: string;
export const V43_READ_ROUTE_FIVE_STEP_UX_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V43_READ_ROUTE_STEP_IDS: readonly string[];
export const V43_READ_ROUTE_OBJECT_IDS: readonly string[];
export const V43_READ_ROUTE_PIPELINE_IDS: readonly string[];
export const V43_READ_ROUTE_SOURCE_SAFE_FIELD_IDS: readonly string[];
export const V43_READ_ROUTE_FORBIDDEN_PAYLOAD_IDS: readonly string[];
export const V43_READ_ROUTE_CONTRACT_ROWS: readonly Record<string, unknown>[];
export function buildV43ReadRouteFiveStepUx(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V43_DEPOSIT_ROUTE_OPTIONS_ARTIFACT_PATH: string;
export const V43_DEPOSIT_ROUTE_OPTIONS_CURRENT_TARGET: string;
export const V43_DEPOSIT_ROUTE_OPTIONS_SCHEMA_ID: string;
export const V43_DEPOSIT_ROUTE_OPTIONS_VERSION: string;
export const V43_DEPOSIT_ROUTE_OPTIONS_SOURCE_SAFETY_VERDICT: string;
export const V43_DEPOSIT_ROUTE_OPTIONS_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V43_DEPOSIT_ROUTE_STEP_IDS: readonly string[];
export const V43_DEPOSIT_OPTION_OBJECT_IDS: readonly string[];
export const V43_DEPOSIT_OPTION_PIPELINE_IDS: readonly string[];
export const V43_DEPOSIT_OPTION_SOURCE_SAFE_FIELD_IDS: readonly string[];
export const V43_DEPOSIT_OPTION_FORBIDDEN_PAYLOAD_IDS: readonly string[];
export const V43_DEPOSIT_ROUTE_OPTIONS_CONTRACT_ROWS: readonly Record<string, unknown>[];
export function buildV43DepositRouteOptions(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V43_DEPOSIT_POLICY_COMPENSATION_ARTIFACT_PATH: string;
export const V43_DEPOSIT_POLICY_COMPENSATION_CURRENT_TARGET: string;
export const V43_DEPOSIT_POLICY_COMPENSATION_SCHEMA_ID: string;
export const V43_DEPOSIT_POLICY_COMPENSATION_VERSION: string;
export const V43_DEPOSIT_POLICY_COMPENSATION_SOURCE_SAFETY_VERDICT: string;
export const V43_DEPOSIT_POLICY_COMPENSATION_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V43_DEPOSIT_POLICY_OBJECT_IDS: readonly string[];
export const V43_DEPOSIT_POLICY_FIELD_IDS: readonly string[];
export const V43_DEPOSIT_POLICY_FORBIDDEN_PAYLOAD_IDS: readonly string[];
export const V43_DEPOSIT_POLICY_COMPENSATION_CONTRACT_ROWS: readonly Record<string, unknown>[];
export function buildV43DepositPolicyCompensation(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V43_DEPOSIT_OPTION_ADMISSION_ARTIFACT_PATH: string;
export const V43_DEPOSIT_OPTION_ADMISSION_CURRENT_TARGET: string;
export const V43_DEPOSIT_OPTION_ADMISSION_SCHEMA_ID: string;
export const V43_DEPOSIT_OPTION_ADMISSION_VERSION: string;
export const V43_DEPOSIT_OPTION_ADMISSION_SOURCE_SAFETY_VERDICT: string;
export const V43_DEPOSIT_OPTION_ADMISSION_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V43_DEPOSIT_OPTION_ADMISSION_OBJECT_IDS: readonly string[];
export const V43_DEPOSIT_OPTION_ADMISSION_FIELD_IDS: readonly string[];
export const V43_DEPOSIT_OPTION_ADMISSION_FORBIDDEN_PAYLOAD_IDS: readonly string[];
export const V43_DEPOSIT_OPTION_ADMISSION_CONTRACT_ROWS: readonly Record<string, unknown>[];
export function buildV43DepositOptionAdmission(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V43_ROUTE_UX_PRODUCT_EXCELLENCE_ARTIFACT_PATH: string;
export const V43_ROUTE_UX_PRODUCT_EXCELLENCE_CURRENT_TARGET: string;
export const V43_ROUTE_UX_PRODUCT_EXCELLENCE_SCHEMA_ID: string;
export const V43_ROUTE_UX_PRODUCT_EXCELLENCE_VERSION: string;
export const V43_ROUTE_UX_PRODUCT_EXCELLENCE_SOURCE_SAFETY_VERDICT: string;
export const V43_ROUTE_UX_PRODUCT_EXCELLENCE_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V43_ROUTE_UX_OBJECT_IDS: readonly string[];
export const V43_ROUTE_UX_FIELD_IDS: readonly string[];
export const V43_ROUTE_UX_FORBIDDEN_PAYLOAD_IDS: readonly string[];
export const V43_ROUTE_UX_CONTRACT_ROWS: readonly Record<string, unknown>[];
export function buildV43RouteUxProductExcellence(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V43_CROSS_ROUTE_REHEARSAL_ARTIFACT_PATH: string;
export const V43_CROSS_ROUTE_REHEARSAL_CURRENT_TARGET: string;
export const V43_CROSS_ROUTE_REHEARSAL_SCHEMA_ID: string;
export const V43_CROSS_ROUTE_REHEARSAL_VERSION: string;
export const V43_CROSS_ROUTE_REHEARSAL_SOURCE_SAFETY_VERDICT: string;
export const V43_CROSS_ROUTE_REHEARSAL_LANE_IDS: readonly string[];
export const V43_CROSS_ROUTE_REHEARSAL_ROUTE_IDS: readonly string[];
export const V43_CROSS_ROUTE_REHEARSAL_STAGE_IDS: readonly string[];
export const V43_CROSS_ROUTE_REHEARSAL_ROW_IDS: readonly string[];
export function buildV43CrossRouteRehearsalTelemetryRepair(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V43_PROMOTION_READINESS_REPORT_ARTIFACT_PATH: string;
export const V43_PROMOTION_READINESS_REPORT_CURRENT_TARGET: string;
export const V43_PROMOTION_READINESS_REPORT_SCHEMA_ID: string;
export const V43_PROMOTION_READINESS_REPORT_VERSION: string;
export const V43_PROMOTION_READINESS_SOURCE_SAFETY_VERDICT: string;
export const V43_PROMOTION_READINESS_GATE_ARTIFACT_PATHS: readonly string[];
export const V43_PROMOTION_READINESS_GENERATED_OUTPUTS: readonly string[];
export function buildV43PromotionReadinessReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export function listMissingV43PromotionReadinessSources(repoRoot?: string): string[];
export const V44_ECONOMIC_DOMAIN_MODEL_ARTIFACT_PATH: string;
export const V44_ECONOMIC_DOMAIN_MODEL_CURRENT_TARGET: string;
export const V44_ECONOMIC_DOMAIN_MODEL_SCHEMA_ID: string;
export const V44_ECONOMIC_DOMAIN_MODEL_VERSION: string;
export const V44_ECONOMIC_DOMAIN_MODEL_SOURCE_SAFETY_VERDICT: string;
export const V44_ECONOMIC_DOMAIN_MODEL_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V44_ECONOMIC_OBJECT_IDS: readonly string[];
export const V44_ECONOMIC_RECEIPT_TAXONOMY_IDS: readonly string[];
export const V44_ECONOMIC_VALUE_LABEL_IDS: readonly string[];
export const V44_ECONOMIC_SOURCE_SAFE_FIELD_IDS: readonly string[];
export const V44_ECONOMIC_FORBIDDEN_PAYLOAD_IDS: readonly string[];
export const V44_ECONOMIC_DOMAIN_ROWS: readonly Record<string, unknown>[];
export function buildV44EconomicDomainModel(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V44_PACKS_PORTFOLIO_MARKET_INTELLIGENCE_ARTIFACT_PATH: string;
export const V44_PACKS_PORTFOLIO_MARKET_INTELLIGENCE_CURRENT_TARGET: string;
export const V44_PACKS_PORTFOLIO_MARKET_INTELLIGENCE_SCHEMA_ID: string;
export const V44_PACKS_PORTFOLIO_MARKET_INTELLIGENCE_VERSION: string;
export const V44_PACKS_PORTFOLIO_MARKET_INTELLIGENCE_SOURCE_SAFETY_VERDICT: string;
export const V44_PACKS_PORTFOLIO_MARKET_INTELLIGENCE_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V44_PACKS_PORTFOLIO_VIEW_IDS: readonly string[];
export const V44_PACKS_MARKET_SIGNAL_IDS: readonly string[];
export const V44_PACKS_MARKET_FACET_IDS: readonly string[];
export const V44_PACKS_PORTFOLIO_FORBIDDEN_PAYLOAD_IDS: readonly string[];
export const V44_PACKS_PORTFOLIO_MARKET_INTELLIGENCE_ROWS: readonly Record<string, unknown>[];
export function buildV44PacksPortfolioMarketIntelligence(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V44_READING_BUDGET_QUOTE_POLICY_ARTIFACT_PATH: string;
export const V44_READING_BUDGET_QUOTE_POLICY_CURRENT_TARGET: string;
export const V44_READING_BUDGET_QUOTE_POLICY_SCHEMA_ID: string;
export const V44_READING_BUDGET_QUOTE_POLICY_VERSION: string;
export const V44_READING_BUDGET_QUOTE_POLICY_SOURCE_SAFETY_VERDICT: string;
export const V44_READING_BUDGET_QUOTE_POLICY_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V44_READING_BUDGET_QUOTE_OBJECT_IDS: readonly string[];
export const V44_READING_BUDGET_STATE_IDS: readonly string[];
export const V44_READING_QUOTE_STATE_IDS: readonly string[];
export const V44_READING_SETTLEMENT_READINESS_IDS: readonly string[];
export const V44_READING_BUDGET_QUOTE_FORBIDDEN_PAYLOAD_IDS: readonly string[];
export const V44_READING_BUDGET_QUOTE_POLICY_ROWS: readonly Record<string, unknown>[];
export function buildV44ReadingBudgetQuotePolicy(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V44_DEPOSITOR_EARNINGS_SUPPLY_OPPORTUNITIES_ARTIFACT_PATH: string;
export const V44_DEPOSITOR_EARNINGS_SUPPLY_OPPORTUNITIES_CURRENT_TARGET: string;
export const V44_DEPOSITOR_EARNINGS_SUPPLY_OPPORTUNITIES_SCHEMA_ID: string;
export const V44_DEPOSITOR_EARNINGS_SUPPLY_OPPORTUNITIES_VERSION: string;
export const V44_DEPOSITOR_EARNINGS_SUPPLY_OPPORTUNITIES_SOURCE_SAFETY_VERDICT: string;
export const V44_DEPOSITOR_EARNINGS_SUPPLY_OPPORTUNITIES_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V44_DEPOSITOR_EARNINGS_SUPPLY_OBJECT_IDS: readonly string[];
export const V44_DEPOSITOR_EARNING_STATE_IDS: readonly string[];
export const V44_DEPOSITOR_SUPPLY_RECOMMENDATION_IDS: readonly string[];
export const V44_DEPOSITOR_DEMAND_OPPORTUNITY_STATE_IDS: readonly string[];
export const V44_DEPOSITOR_EARNINGS_SUPPLY_FORBIDDEN_PAYLOAD_IDS: readonly string[];
export const V44_DEPOSITOR_EARNINGS_SUPPLY_ROWS: readonly Record<string, unknown>[];
export function buildV44DepositorEarningsSupplyOpportunities(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V44_BTD_BTC_COMPENSATION_STATEMENTS_ARTIFACT_PATH: string;
export const V44_BTD_BTC_COMPENSATION_STATEMENTS_CURRENT_TARGET: string;
export const V44_BTD_BTC_COMPENSATION_STATEMENTS_SCHEMA_ID: string;
export const V44_BTD_BTC_COMPENSATION_STATEMENTS_VERSION: string;
export const V44_BTD_BTC_COMPENSATION_STATEMENTS_SOURCE_SAFETY_VERDICT: string;
export const V44_BTD_BTC_COMPENSATION_STATEMENTS_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V44_BTD_BTC_COMPENSATION_OBJECT_IDS: readonly string[];
export const V44_BTD_BTC_ACCOUNTING_STATE_IDS: readonly string[];
export const V44_BTD_RANGE_ACCOUNTING_STATE_IDS: readonly string[];
export const V44_BTC_SETTLEMENT_ACCOUNTING_STATE_IDS: readonly string[];
export const V44_CONTRIBUTOR_COMPENSATION_STATE_IDS: readonly string[];
export const V44_BTD_BTC_COMPENSATION_VALUE_LABEL_IDS: readonly string[];
export const V44_BTD_BTC_COMPENSATION_FORBIDDEN_PAYLOAD_IDS: readonly string[];
export const V44_BTD_BTC_COMPENSATION_ROWS: readonly Record<string, unknown>[];
export function buildV44BtdBtcCompensationStatements(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V44_ORGANIZATION_POLICY_WALLET_AUTHORITY_ARTIFACT_PATH: string;
export const V44_ORGANIZATION_POLICY_WALLET_AUTHORITY_CURRENT_TARGET: string;
export const V44_ORGANIZATION_POLICY_WALLET_AUTHORITY_SCHEMA_ID: string;
export const V44_ORGANIZATION_POLICY_WALLET_AUTHORITY_VERSION: string;
export const V44_ORGANIZATION_POLICY_WALLET_AUTHORITY_SOURCE_SAFETY_VERDICT: string;
export const V44_ORGANIZATION_POLICY_OBJECT_IDS: readonly string[];
export const V44_ORGANIZATION_POLICY_ROUTE_IDS: readonly string[];
export const V44_ORGANIZATION_POLICY_ACTION_IDS: readonly string[];
export const V44_ORGANIZATION_POLICY_STATE_IDS: readonly string[];
export const V44_ORGANIZATION_POLICY_FORBIDDEN_PAYLOAD_IDS: readonly string[];
export const V44_ORGANIZATION_POLICY_ROWS: readonly Record<string, unknown>[];
export function buildV44OrganizationPolicyWalletAuthority(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V44_ENTERPRISE_PRODUCT_UX_ARTIFACT_PATH: string;
export const V44_ENTERPRISE_PRODUCT_UX_CURRENT_TARGET: string;
export const V44_ENTERPRISE_PRODUCT_UX_SCHEMA_ID: string;
export const V44_ENTERPRISE_PRODUCT_UX_VERSION: string;
export const V44_ENTERPRISE_PRODUCT_UX_SOURCE_SAFETY_VERDICT: string;
export const V44_ENTERPRISE_PRODUCT_UX_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V44_ENTERPRISE_PRODUCT_UX_OBJECT_IDS: readonly string[];
export const V44_ENTERPRISE_PRODUCT_UX_ROUTE_IDS: readonly string[];
export const V44_ENTERPRISE_PRODUCT_UX_CAPABILITY_IDS: readonly string[];
export const V44_ENTERPRISE_PRODUCT_UX_FORBIDDEN_PAYLOAD_IDS: readonly string[];
export const V44_ENTERPRISE_PRODUCT_UX_ROWS: readonly Record<string, unknown>[];
export function buildV44EnterpriseProductUx(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V44_SCALED_NETWORK_REHEARSAL_ARTIFACT_PATH: string;
export const V44_SCALED_NETWORK_REHEARSAL_CURRENT_TARGET: string;
export const V44_SCALED_NETWORK_REHEARSAL_SCHEMA_ID: string;
export const V44_SCALED_NETWORK_REHEARSAL_VERSION: string;
export const V44_SCALED_NETWORK_REHEARSAL_SOURCE_SAFETY_VERDICT: string;
export const V44_SCALED_NETWORK_REHEARSAL_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V44_SCALED_NETWORK_REHEARSAL_LANE_IDS: readonly string[];
export const V44_SCALED_NETWORK_REHEARSAL_ROUTE_IDS: readonly string[];
export const V44_SCALED_NETWORK_REHEARSAL_STAGE_IDS: readonly string[];
export const V44_SCALED_NETWORK_REHEARSAL_ROW_IDS: readonly string[];
export const V44_SCALED_NETWORK_REHEARSAL_MINIMUM_COUNTS: Readonly<Record<string, number>>;
export const V44_SCALED_NETWORK_REHEARSAL_FORBIDDEN_PAYLOAD_IDS: readonly string[];
export const V44_SCALED_NETWORK_REHEARSAL_ROWS: readonly Record<string, unknown>[];
export function buildV44ScaledNetworkRehearsal(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V44_PROMOTION_READINESS_REPORT_ARTIFACT_PATH: string;
export const V44_PROMOTION_READINESS_REPORT_CURRENT_TARGET: string;
export const V44_PROMOTION_READINESS_REPORT_SCHEMA_ID: string;
export const V44_PROMOTION_READINESS_REPORT_VERSION: string;
export const V44_PROMOTION_READINESS_SOURCE_SAFETY_VERDICT: string;
export const V44_PROMOTION_READINESS_GATE_ARTIFACT_PATHS: readonly string[];
export const V44_PROMOTION_READINESS_GENERATED_OUTPUTS: readonly string[];
export function buildV44PromotionReadinessReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export function listMissingV44PromotionReadinessSources(repoRoot?: string): string[];
export const V45_PROOF_FAMILY_VERSION: string;
export const V45_PROOF_FAMILY_CURRENT_TARGET: string;
export const V45_PROOF_FAMILY_SCHEMA_ID: string;
export const V45_PROOF_FAMILY_SOURCE_SAFETY_VERDICT: string;
export const V45_PROOF_FAMILY_GENERATED_AT: string;
export const V45_PROOF_FAMILY_PROOF_SOURCE_COMMIT: string;
export const V45_PROOF_FAMILY_PROVEN_PATH: string;
export const V45_PROOF_FAMILY_ARTIFACT_PATHS: readonly string[];
export const V45_PROOF_FAMILY_GENERATED_OUTPUTS: readonly string[];
export const V45_PROOF_FAMILY_IDS: readonly string[];
export const V45_PROOF_FAMILY_DEFINITIONS: readonly Record<string, unknown>[];
export function buildV45ProofFamilyArtifact(input?: Record<string, unknown>): BitcodeProtocolReport;
export function buildV45ProofFamilyArtifacts(input?: Record<string, unknown>): BitcodeProtocolReport & {
  artifacts: BitcodeProtocolReport[];
};
export function buildV45ProofFamilyProvenMarkdown(input: Record<string, unknown>): string;
export const V45_SOURCE_SAFE_E2E_REHEARSAL_ARTIFACT_PATH: string;
export const V45_SOURCE_SAFE_E2E_REHEARSAL_CURRENT_TARGET: string;
export const V45_SOURCE_SAFE_E2E_REHEARSAL_SCHEMA_ID: string;
export const V45_SOURCE_SAFE_E2E_REHEARSAL_VERSION: string;
export const V45_SOURCE_SAFE_E2E_REHEARSAL_SOURCE_SAFETY_VERDICT: string;
export const V45_SOURCE_SAFE_E2E_REHEARSAL_LANE_IDS: readonly string[];
export const V45_SOURCE_SAFE_E2E_REHEARSAL_STAGE_IDS: readonly string[];
export const V45_SOURCE_SAFE_E2E_REHEARSAL_EVIDENCE_CLASS_IDS: readonly string[];
export const V45_SOURCE_SAFE_E2E_REHEARSAL_ROW_IDS: readonly string[];
export const V45_SOURCE_SAFE_E2E_REHEARSAL_FORBIDDEN_PAYLOAD_CLASSES: readonly string[];
export const V45_SOURCE_SAFE_E2E_REHEARSAL_ROWS: readonly Record<string, unknown>[];
export const V45_SOURCE_SAFE_E2E_REHEARSAL_SOURCE_ROOTS: Readonly<Record<string, string>>;
export function buildV45SourceSafeEndToEndRehearsal(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V45_PROMOTION_READINESS_REPORT_ARTIFACT_PATH: string;
export const V45_PROMOTION_READINESS_REPORT_CURRENT_TARGET: string;
export const V45_PROMOTION_READINESS_REPORT_SCHEMA_ID: string;
export const V45_PROMOTION_READINESS_REPORT_VERSION: string;
export const V45_PROMOTION_READINESS_SOURCE_SAFETY_VERDICT: string;
export const V45_PROMOTION_READINESS_GATE_ARTIFACT_PATHS: readonly string[];
export const V45_PROMOTION_READINESS_GENERATED_OUTPUTS: readonly string[];
export function buildV45PromotionReadinessReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export function listMissingV45PromotionReadinessSources(repoRoot?: string): string[];
export const V46_PROTOCOL_COMPREHENSION_OBJECT_MODEL_ARTIFACT_PATH: string;
export const V46_PROTOCOL_COMPREHENSION_OBJECT_MODEL_CURRENT_TARGET: string;
export const V46_PROTOCOL_COMPREHENSION_OBJECT_MODEL_SCHEMA_ID: string;
export const V46_PROTOCOL_COMPREHENSION_OBJECT_MODEL_VERSION: string;
export const V46_PROTOCOL_COMPREHENSION_OBJECT_MODEL_SOURCE_SAFETY_VERDICT: string;
export const V46_PROTOCOL_COMPREHENSION_OBJECT_MODEL_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V46_PROTOCOL_COMPREHENSION_OBJECT_IDS: readonly string[];
export const V46_PROTOCOL_CLAIM_CATEGORY_IDS: readonly string[];
export const V46_PROTOCOL_CLAIM_AUTHORITY_IDS: readonly string[];
export const V46_PROTOCOL_DISCLOSURE_BOUNDARY_IDS: readonly string[];
export const V46_PROTOCOL_FORBIDDEN_CLAIM_IDS: readonly string[];
export const V46_PROTOCOL_SOURCE_SAFE_FIELD_IDS: readonly string[];
export const V46_PROTOCOL_PRIVATE_PAYLOAD_IDS: readonly string[];
export const V46_PROTOCOL_OBJECT_ROWS: readonly Record<string, unknown>[];
export const V46_PROTOCOL_CLAIM_ROWS: readonly Record<string, unknown>[];
export function buildV46ProtocolComprehensionObjectModel(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V46_PUBLIC_OPERATOR_CLAIM_BOUNDARIES_ARTIFACT_PATH: string;
export const V46_PUBLIC_OPERATOR_CLAIM_BOUNDARIES_CURRENT_TARGET: string;
export const V46_PUBLIC_OPERATOR_CLAIM_BOUNDARIES_SCHEMA_ID: string;
export const V46_PUBLIC_OPERATOR_CLAIM_BOUNDARIES_VERSION: string;
export const V46_PUBLIC_OPERATOR_CLAIM_BOUNDARIES_SOURCE_SAFETY_VERDICT: string;
export const V46_PUBLIC_OPERATOR_CLAIM_BOUNDARIES_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V46_PUBLIC_OPERATOR_SURFACE_IDS: readonly string[];
export const V46_PUBLIC_OPERATOR_SURFACE_KIND_IDS: readonly string[];
export const V46_PUBLIC_OPERATOR_ALLOWED_DATA_CLASSES: readonly string[];
export const V46_PUBLIC_OPERATOR_SURFACE_ROWS: readonly Record<string, unknown>[];
export function buildV46PublicOperatorClaimBoundaries(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V46_PRODUCT_ROUTE_COMPREHENSION_READBACK_ARTIFACT_PATH: string;
export const V46_PRODUCT_ROUTE_COMPREHENSION_READBACK_CURRENT_TARGET: string;
export const V46_PRODUCT_ROUTE_COMPREHENSION_READBACK_SCHEMA_ID: string;
export const V46_PRODUCT_ROUTE_COMPREHENSION_READBACK_VERSION: string;
export const V46_PRODUCT_ROUTE_COMPREHENSION_READBACK_SOURCE_SAFETY_VERDICT: string;
export const V46_PRODUCT_ROUTE_COMPREHENSION_READBACK_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V46_PRODUCT_ROUTE_IDS: readonly string[];
export const V46_PRODUCT_ROUTE_PATHS: readonly string[];
export const V46_PRODUCT_ROUTE_CAPABILITY_IDS: readonly string[];
export const V46_PRODUCT_ROUTE_READBACK_ROWS: readonly Record<string, unknown>[];
export function buildV46ProductRouteComprehensionReadback(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V46_INTERFACE_CLAIM_CONTRACTS_ARTIFACT_PATH: string;
export const V46_INTERFACE_CLAIM_CONTRACTS_CURRENT_TARGET: string;
export const V46_INTERFACE_CLAIM_CONTRACTS_SCHEMA_ID: string;
export const V46_INTERFACE_CLAIM_CONTRACTS_VERSION: string;
export const V46_INTERFACE_CLAIM_CONTRACTS_SOURCE_SAFETY_VERDICT: string;
export const V46_INTERFACE_CLAIM_CONTRACTS_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V46_INTERFACE_CLAIM_SURFACE_IDS: readonly string[];
export const V46_INTERFACE_CLAIM_CAPABILITY_IDS: readonly string[];
export const V46_INTERFACE_CLAIM_CONTRACT_ROWS: readonly Record<string, unknown>[];
export function buildV46InterfaceClaimContracts(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V46_PROOF_READBACK_OPERATOR_EXPLANATION_ARTIFACT_PATH: string;
export const V46_PROOF_READBACK_OPERATOR_EXPLANATION_CURRENT_TARGET: string;
export const V46_PROOF_READBACK_OPERATOR_EXPLANATION_SCHEMA_ID: string;
export const V46_PROOF_READBACK_OPERATOR_EXPLANATION_VERSION: string;
export const V46_PROOF_READBACK_OPERATOR_EXPLANATION_SOURCE_SAFETY_VERDICT: string;
export const V46_PROOF_READBACK_OPERATOR_EXPLANATION_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V46_PROOF_READBACK_EVIDENCE_CLASS_IDS: readonly string[];
export const V46_PROOF_READBACK_REQUIRED_OPERATOR_QUESTION_IDS: readonly string[];
export const V46_PROOF_READBACK_OPERATOR_DECISION_IDS: readonly string[];
export const V46_PROOF_READBACK_OPERATOR_EXPLANATION_ROWS: readonly Record<string, unknown>[];
export function buildV46ProofReadbackOperatorExplanation(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V46_LOCAL_INTERFACE_COMPREHENSION_REHEARSAL_ARTIFACT_PATH: string;
export const V46_LOCAL_INTERFACE_COMPREHENSION_REHEARSAL_CURRENT_TARGET: string;
export const V46_LOCAL_INTERFACE_COMPREHENSION_REHEARSAL_SCHEMA_ID: string;
export const V46_LOCAL_INTERFACE_COMPREHENSION_REHEARSAL_VERSION: string;
export const V46_LOCAL_INTERFACE_COMPREHENSION_REHEARSAL_SOURCE_SAFETY_VERDICT: string;
export const V46_LOCAL_INTERFACE_COMPREHENSION_REHEARSAL_SOURCE_ROOTS: Readonly<Record<string, string>>;
export const V46_LOCAL_INTERFACE_REHEARSAL_SURFACE_IDS: readonly string[];
export const V46_LOCAL_INTERFACE_REHEARSAL_STEP_IDS: readonly string[];
export const V46_LOCAL_INTERFACE_REHEARSAL_REQUIRED_ARTIFACT_IDS: readonly string[];
export const V46_LOCAL_INTERFACE_COMPREHENSION_REHEARSAL_ROWS: readonly Record<string, unknown>[];
export function buildV46LocalInterfaceComprehensionRehearsal(input?: Record<string, unknown>): BitcodeProtocolReport;
export const V46_PROMOTION_READINESS_REPORT_ARTIFACT_PATH: string;
export const V46_PROMOTION_READINESS_REPORT_CURRENT_TARGET: string;
export const V46_PROMOTION_READINESS_REPORT_SCHEMA_ID: string;
export const V46_PROMOTION_READINESS_REPORT_VERSION: string;
export const V46_PROMOTION_READINESS_SOURCE_SAFETY_VERDICT: string;
export const V46_PROMOTION_READINESS_GATE_ARTIFACT_PATHS: readonly string[];
export const V46_PROMOTION_READINESS_GENERATED_OUTPUTS: readonly string[];
export function buildV46PromotionReadinessReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export function listMissingV46PromotionReadinessSources(repoRoot?: string): string[];
export const EXCHANGE_INTENT_ORDER_CONTRACTS_ARTIFACT_PATH: string;
export const EXCHANGE_INTENT_ORDER_CONTRACTS_CURRENT_TARGET: string;
export const EXCHANGE_INTENT_ORDER_CONTRACTS_SCHEMA_ID: string;
export const EXCHANGE_INTENT_ORDER_CONTRACTS_VERSION: string;
export const EXCHANGE_INTENT_ORDER_CONTRACTS_SOURCE_SAFETY_VERDICT: string;
export const EXCHANGE_INTENT_ACTION_KINDS: readonly string[];
export const EXCHANGE_ORDER_TRANSITION_IDS: readonly string[];
export const EXCHANGE_INTENT_REQUIRED_FIELD_IDS: readonly string[];
export const EXCHANGE_ORDER_REQUIRED_FIELD_IDS: readonly string[];
export const EXCHANGE_INTENT_ORDER_ROWS: readonly Record<string, unknown>[];
export function buildExchangeIntentOrderContracts(input?: Record<string, unknown>): BitcodeProtocolReport;
export const EXCHANGE_RIGHTS_TRANSFER_REVIEW_ARTIFACT_PATH: string;
export const EXCHANGE_RIGHTS_TRANSFER_REVIEW_CURRENT_TARGET: string;
export const EXCHANGE_RIGHTS_TRANSFER_REVIEW_SCHEMA_ID: string;
export const EXCHANGE_RIGHTS_TRANSFER_REVIEW_VERSION: string;
export const EXCHANGE_RIGHTS_TRANSFER_REVIEW_SOURCE_SAFETY_VERDICT: string;
export const EXCHANGE_RIGHTS_TRANSFER_PREVIEW_STATES: readonly string[];
export const EXCHANGE_RIGHTS_TRANSFER_REQUIRED_FIELD_IDS: readonly string[];
export const EXCHANGE_RIGHTS_TRANSFER_PREVIEW_ROWS: readonly Record<string, unknown>[];
export function buildExchangeRightsTransferReview(input?: Record<string, unknown>): BitcodeProtocolReport;
export const EXCHANGE_PRICING_QUOTE_ARTIFACT_PATH: string;
export const EXCHANGE_PRICING_QUOTE_CURRENT_TARGET: string;
export const EXCHANGE_PRICING_QUOTE_SCHEMA_ID: string;
export const EXCHANGE_PRICING_QUOTE_VERSION: string;
export const EXCHANGE_PRICING_QUOTE_SOURCE_SAFETY_VERDICT: string;
export const EXCHANGE_PRICING_QUOTE_STATES: readonly string[];
export const EXCHANGE_PRICING_LIQUIDITY_BANDS: readonly string[];
export const EXCHANGE_PRICING_QUOTE_REQUIRED_FIELD_IDS: readonly string[];
export const EXCHANGE_PRICING_QUOTE_ROWS: readonly Record<string, unknown>[];
export function buildExchangePricingQuote(input?: Record<string, unknown>): BitcodeProtocolReport;
export const EXCHANGE_SETTLEMENT_RECONCILIATION_ARTIFACT_PATH: string;
export const EXCHANGE_SETTLEMENT_RECONCILIATION_CURRENT_TARGET: string;
export const EXCHANGE_SETTLEMENT_RECONCILIATION_SCHEMA_ID: string;
export const EXCHANGE_SETTLEMENT_RECONCILIATION_VERSION: string;
export const EXCHANGE_SETTLEMENT_RECONCILIATION_SOURCE_SAFETY_VERDICT: string;
export const EXCHANGE_SETTLEMENT_RECEIPT_STATES: readonly string[];
export const EXCHANGE_SETTLEMENT_REQUIRED_FIELD_IDS: readonly string[];
export const EXCHANGE_SETTLEMENT_RECEIPT_ROWS: readonly Record<string, unknown>[];
export function buildExchangeSettlementReconciliation(input?: Record<string, unknown>): BitcodeProtocolReport;
export const EXCHANGE_DISPUTE_REPAIR_REVENUE_ROUTE_ARTIFACT_PATH: string;
export const EXCHANGE_DISPUTE_REPAIR_REVENUE_ROUTE_CURRENT_TARGET: string;
export const EXCHANGE_DISPUTE_REPAIR_REVENUE_ROUTE_SCHEMA_ID: string;
export const EXCHANGE_DISPUTE_REPAIR_REVENUE_ROUTE_VERSION: string;
export const EXCHANGE_DISPUTE_REPAIR_REVENUE_ROUTE_SOURCE_SAFETY_VERDICT: string;
export const EXCHANGE_DISPUTE_INCIDENT_CLASSES: readonly string[];
export const EXCHANGE_REVENUE_ROUTE_STATES: readonly string[];
export const EXCHANGE_DISPUTE_REPAIR_CASE_REQUIRED_FIELD_IDS: readonly string[];
export const EXCHANGE_REVENUE_ROUTE_REQUIRED_FIELD_IDS: readonly string[];
export const EXCHANGE_DISPUTE_REPAIR_CASE_ROWS: readonly Record<string, unknown>[];
export const EXCHANGE_REVENUE_ROUTE_ROWS: readonly Record<string, unknown>[];
export function buildExchangeDisputeRepairRevenueRoute(input?: Record<string, unknown>): BitcodeProtocolReport;
export const EXCHANGE_UX_PROOF_ARTIFACT_PATH: string;
export const EXCHANGE_UX_PROOF_CURRENT_TARGET: string;
export const EXCHANGE_UX_PROOF_SCHEMA_ID: string;
export const EXCHANGE_UX_PROOF_VERSION: string;
export const EXCHANGE_UX_PROOF_SOURCE_SAFETY_VERDICT: string;
export const EXCHANGE_UX_CAPABILITY_IDS: readonly string[];
export const EXCHANGE_UX_ROUTE_IDS: readonly string[];
export const EXCHANGE_UX_SOURCE_SAFE_DETAIL_IDS: readonly string[];
export const EXCHANGE_UX_PROOF_ROWS: readonly Record<string, unknown>[];
export function buildExchangeUxProof(input?: Record<string, unknown>): BitcodeProtocolReport;
export const EXCHANGE_REHEARSAL_ARTIFACT_PATH: string;
export const EXCHANGE_REHEARSAL_CURRENT_TARGET: string;
export const EXCHANGE_REHEARSAL_SCHEMA_ID: string;
export const EXCHANGE_REHEARSAL_VERSION: string;
export const EXCHANGE_REHEARSAL_SOURCE_SAFETY_VERDICT: string;
export const EXCHANGE_REHEARSAL_IDS: readonly string[];
export const EXCHANGE_REHEARSAL_FLOW_IDS: readonly string[];
export const EXCHANGE_REHEARSAL_ROWS: readonly Record<string, unknown>[];
export function buildExchangeRehearsal(input?: Record<string, unknown>): BitcodeProtocolReport;
export const DOCUMENTATION_SURFACE_CATALOG_ARTIFACT_PATH: string;
export const DOCUMENTATION_SURFACE_CATALOG_CURRENT_TARGET: string;
export const DOCUMENTATION_SURFACE_CATALOG_SCHEMA_ID: string;
export const DOCUMENTATION_SURFACE_CATALOG_VERSION: string;
export const DOCUMENTATION_SURFACE_SOURCE_SAFETY_VERDICT: string;
export const DOCUMENTATION_SURFACE_IDS: readonly string[];
export const DOCUMENTATION_SURFACE_ROWS: readonly Record<string, unknown>[];
export function buildDocumentationSurfaceCatalog(input?: Record<string, unknown>): BitcodeProtocolReport;
export const TELEMETRY_TAXONOMY_CATALOG_ARTIFACT_PATH: string;
export const TELEMETRY_TAXONOMY_CATALOG_CURRENT_TARGET: string;
export const TELEMETRY_TAXONOMY_CATALOG_SCHEMA_ID: string;
export const TELEMETRY_TAXONOMY_CATALOG_VERSION: string;
export const TELEMETRY_TAXONOMY_SOURCE_SAFETY_VERDICT: string;
export const TELEMETRY_EVENT_FAMILIES: readonly string[];
export const TELEMETRY_TAXONOMY_ROWS: readonly Record<string, unknown>[];
export function buildTelemetryTaxonomyCatalog(input?: Record<string, unknown>): BitcodeProtocolReport;
export const PUBLIC_DOCS_USAGE_GUIDE_CATALOG_ARTIFACT_PATH: string;
export const PUBLIC_DOCS_USAGE_GUIDE_CATALOG_CURRENT_TARGET: string;
export const PUBLIC_DOCS_USAGE_GUIDE_CATALOG_SCHEMA_ID: string;
export const PUBLIC_DOCS_USAGE_GUIDE_CATALOG_VERSION: string;
export const PUBLIC_DOCS_USAGE_GUIDE_SOURCE_SAFETY_VERDICT: string;
export const PUBLIC_DOCS_USAGE_GUIDE_IDS: readonly string[];
export const PUBLIC_DOCS_USAGE_GUIDE_ROWS: readonly Record<string, unknown>[];
export function buildPublicDocsUsageGuideCatalog(input?: Record<string, unknown>): BitcodeProtocolReport;
export const OPERATOR_RUNBOOK_CATALOG_ARTIFACT_PATH: string;
export const OPERATOR_RUNBOOK_CATALOG_CURRENT_TARGET: string;
export const OPERATOR_RUNBOOK_CATALOG_SCHEMA_ID: string;
export const OPERATOR_RUNBOOK_CATALOG_VERSION: string;
export const OPERATOR_RUNBOOK_SOURCE_SAFETY_VERDICT: string;
export const OPERATOR_RUNBOOK_IDS: readonly string[];
export const OPERATOR_RUNBOOK_ROWS: readonly Record<string, unknown>[];
export function buildOperatorRunbookCatalog(input?: Record<string, unknown>): BitcodeProtocolReport;
export const DOCS_QA_ALIGNMENT_REPORT_ARTIFACT_PATH: string;
export const DOCS_QA_ALIGNMENT_REPORT_CURRENT_TARGET: string;
export const DOCS_QA_ALIGNMENT_REPORT_SCHEMA_ID: string;
export const DOCS_QA_ALIGNMENT_REPORT_VERSION: string;
export const DOCS_QA_ALIGNMENT_SOURCE_SAFETY_VERDICT: string;
export const DOCS_QA_ALIGNMENT_IDS: readonly string[];
export const DOCS_QA_ALIGNMENT_ROWS: readonly Record<string, unknown>[];
export function buildDocsQaAlignmentReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export const TESTNET_ROLLOUT_READINESS_GUIDE_ARTIFACT_PATH: string;
export const TESTNET_ROLLOUT_READINESS_GUIDE_CURRENT_TARGET: string;
export const TESTNET_ROLLOUT_READINESS_GUIDE_SCHEMA_ID: string;
export const TESTNET_ROLLOUT_READINESS_GUIDE_VERSION: string;
export const TESTNET_ROLLOUT_READINESS_SOURCE_SAFETY_VERDICT: string;
export const TESTNET_ROLLOUT_GUIDE_IDS: readonly string[];
export const TESTNET_ROLLOUT_LANE_IDS: readonly string[];
export const TESTNET_ROLLOUT_READINESS_ROWS: readonly Record<string, unknown>[];
export function buildTestnetRolloutReadinessGuide(input?: Record<string, unknown>): BitcodeProtocolReport;
export const TELEMETRY_DOCUMENTATION_INTERFACE_INTEGRATION_ARTIFACT_PATH: string;
export const TELEMETRY_DOCUMENTATION_INTERFACE_INTEGRATION_CURRENT_TARGET: string;
export const TELEMETRY_DOCUMENTATION_INTERFACE_INTEGRATION_SCHEMA_ID: string;
export const TELEMETRY_DOCUMENTATION_INTERFACE_INTEGRATION_VERSION: string;
export const TELEMETRY_DOCUMENTATION_INTERFACE_INTEGRATION_SOURCE_SAFETY_VERDICT: string;
export const TELEMETRY_DOCUMENTATION_INTERFACE_IDS: readonly string[];
export const TELEMETRY_DOCUMENTATION_INTERFACE_ROWS: readonly Record<string, unknown>[];
export function buildTelemetryDocumentationInterfaceIntegration(input?: Record<string, unknown>): BitcodeProtocolReport;
export const LOCAL_STAGING_TELEMETRY_DOCUMENTATION_REHEARSAL_ARTIFACT_PATH: string;
export const LOCAL_STAGING_TELEMETRY_DOCUMENTATION_REHEARSAL_CURRENT_TARGET: string;
export const LOCAL_STAGING_TELEMETRY_DOCUMENTATION_REHEARSAL_SCHEMA_ID: string;
export const LOCAL_STAGING_TELEMETRY_DOCUMENTATION_REHEARSAL_VERSION: string;
export const LOCAL_STAGING_TELEMETRY_DOCUMENTATION_REHEARSAL_SOURCE_SAFETY_VERDICT: string;
export const LOCAL_STAGING_TELEMETRY_DOCUMENTATION_REHEARSAL_IDS: readonly string[];
export const LOCAL_STAGING_TELEMETRY_DOCUMENTATION_REHEARSAL_ROWS: readonly Record<string, unknown>[];
export function buildLocalStagingTelemetryDocumentationRehearsal(input?: Record<string, unknown>): BitcodeProtocolReport;
export const DOCUMENTATION_TELEMETRY_PROMOTION_READINESS_REPORT_ARTIFACT_PATH: string;
export const DOCUMENTATION_TELEMETRY_PROMOTION_READINESS_REPORT_CURRENT_TARGET: string;
export const DOCUMENTATION_TELEMETRY_PROMOTION_READINESS_REPORT_SCHEMA_ID: string;
export const DOCUMENTATION_TELEMETRY_PROMOTION_READINESS_REPORT_VERSION: string;
export const DOCUMENTATION_TELEMETRY_PROMOTION_READINESS_SOURCE_SAFETY_VERDICT: string;
export const DOCUMENTATION_TELEMETRY_PROMOTION_READINESS_GATE_ARTIFACT_PATHS: readonly string[];
export const DOCUMENTATION_TELEMETRY_PROMOTION_READINESS_GENERATED_OUTPUTS: readonly string[];
export function buildDocumentationTelemetryPromotionReadinessReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export const EXCHANGE_PROMOTION_READINESS_REPORT_ARTIFACT_PATH: string;
export const EXCHANGE_PROMOTION_READINESS_REPORT_CURRENT_TARGET: string;
export const EXCHANGE_PROMOTION_READINESS_REPORT_SCHEMA_ID: string;
export const EXCHANGE_PROMOTION_READINESS_REPORT_VERSION: string;
export const EXCHANGE_PROMOTION_READINESS_SOURCE_SAFETY_VERDICT: string;
export const EXCHANGE_PROMOTION_READINESS_GATE_ARTIFACT_PATHS: readonly string[];
export const EXCHANGE_PROMOTION_READINESS_GENERATED_OUTPUTS: readonly string[];
export function buildExchangePromotionReadinessReport(input?: Record<string, unknown>): BitcodeProtocolReport;
export function defaultProvenOutputPath(version: string): string;
export function generateCanonicalProvenMarkdown(input?: Record<string, unknown>): BitcodeProvenMarkdownPackage;
