module.exports = {
  preset: 'ts-jest/presets/js-with-ts',
  testEnvironment: 'node',
  testMatch: ['**/__tests__/**/*.test.(ts|tsx)'],
  roots: ['<rootDir>'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  moduleNameMapper: {
    '^@bitcode/pipelines-generics$': '<rootDir>/../pipelines-generics/src/index.ts',
    '^@bitcode/pipelines-generics/(.*)$': '<rootDir>/../pipelines-generics/src/$1',
    // nested generic-llms family (not packages/generic-llms/src)
    '^@bitcode/generation-generics$': '<rootDir>/../generation-generics/src/index.ts',
    '^@bitcode/generic-generations-failsafes$': '<rootDir>/../generic-generations/failsafes/src/index.ts',
    '^@bitcode/generic-generations-thinkings$': '<rootDir>/../generic-generations/thinkings/src/index.ts',
    '^@bitcode/generic-llms$': '<rootDir>/../generic-llms/registry/src/index.ts',
    '^@bitcode/generic-llms/defaults$': '<rootDir>/../generic-llms/defaults/src/index.ts',
    '^@bitcode/generic-llms-defaults$': '<rootDir>/../generic-llms/defaults/src/index.ts',
    '^@bitcode/generic-llms-xai$': '<rootDir>/../generic-llms/xAI/src/index.ts',
    '^@bitcode/generic-llms-openai$': '<rootDir>/../generic-llms/OpenAI/src/index.ts',
    '^@bitcode/generic-llms-anthropic$': '<rootDir>/../generic-llms/Anthropic/src/index.ts',
    '^@bitcode/generic-llms-google$': '<rootDir>/../generic-llms/Google/src/index.ts',
    '^@bitcode/logger$': '<rootDir>/../logger/src/index.ts',
    '^@bitcode/parsing$': '<rootDir>/../parsing/src/parsing.ts',
    '^@bitcode/streams$': '<rootDir>/../streams/src/index.ts',
    '^@bitcode/supabase$': '<rootDir>/../supabase/src/index.ts',
    '^@bitcode/artifacts$': '<rootDir>/../artifacts/src/artifacts.ts',
    '^@bitcode/([^/]+)$': '<rootDir>/../$1/src/index.ts',
    '^@bitcode/([^/]+)/(.*)$': '<rootDir>/../$1/src/$2',
  },
  globals: {
    'ts-jest': {
      tsconfig: '<rootDir>/../../tsconfig.json',
      diagnostics: false,
    },
  },
};
