/**
 * Jest configuration for the AssetPack pipeline
 */
module.exports = {
  preset: 'ts-jest/presets/js-with-ts',
  testEnvironment: 'node',
  testMatch: ['**/__tests__/**/*.test.(ts|tsx)'],
  testPathIgnorePatterns: ['/node_modules/', '/dist/'],
  roots: ['<rootDir>'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  globals: {
    'ts-jest': {
      tsconfig: '<rootDir>/../../../../tsconfig.json',
      diagnostics: false,
    },
  },
  // Map workspace aliases used in tests to source files so Jest can resolve them
  moduleNameMapper: {
    '^@bitcode/pipelines-generics$': '<rootDir>/../../../pipelines-generics/src/index.ts',
    // Dual deep-import styles: some callers include `/src/`, SDIVF omits it
    // (matches root tsconfig `@bitcode/pipelines-generics/*` → `src/*`).
    '^@bitcode/pipelines-generics/src/(.*)$': '<rootDir>/../../../pipelines-generics/src/$1',
    '^@bitcode/pipelines-generics/(.*)$': '<rootDir>/../../../pipelines-generics/src/$1',
    '^@bitcode/generic-pipelines-execution-pipeline-sdivf$': '<rootDir>/../../../generic-pipelines/execution-pipeline-sdivf/src/index.ts',
    '^@bitcode/generic-pipelines-execution-pipeline-sdivf/(.*)$': '<rootDir>/../../../generic-pipelines/execution-pipeline-sdivf/src/$1',
    '^@bitcode/execution-generics$': '<rootDir>/../../../execution-generics/src/index.ts',
    '^@bitcode/execution-generics/(.*)$': '<rootDir>/../../../execution-generics/src/$1',
    '^@bitcode/agent-generics$': '<rootDir>/../../../agent-generics/src/index.ts',
    '^@bitcode/agent-generics/(.*)$': '<rootDir>/../../../agent-generics/src/$1',
    '^@bitcode/generic-tools/(.*)$': '<rootDir>/../../../generic-tools/$1/src/index.ts',
    '^@bitcode/api/streams$': '<rootDir>/../../../api/src/streams/index.ts',
    '^@bitcode/api/streams/(.*)$': '<rootDir>/../../../api/src/streams/$1',
    '^@bitcode/generation-generics$': '<rootDir>/../../../generation-generics/src/index.ts',
    '^@bitcode/generic-generations-failsafes$': '<rootDir>/../../../generic-generations/failsafes/src/index.ts',
    '^@bitcode/generic-generations-thinkings$': '<rootDir>/../../../generic-generations/thinkings/src/index.ts',
    '^@bitcode/measurement-generics$': '<rootDir>/../../../measurement-generics/src/index.ts',
    '^@bitcode/generic-agents-agent-measure$': '<rootDir>/../../../generic-agents/agent-measure/src/index.ts',
    '^@bitcode/generic-agents-agent-measure-absolutes$': '<rootDir>/../../../generic-agents/agent-measure-absolutes/src/index.ts',
    '^@bitcode/generic-measurements-needinesses$': '<rootDir>/../../../generic-measurements/needinesses/src/index.ts',
    '^@bitcode/asset-packs-generics$': '<rootDir>/../../../asset-packs-generics/src/index.ts',
    '^@bitcode/asset-packs-generics/(.*)$': '<rootDir>/../../../asset-packs-generics/src/$1',
    '^@bitcode/generic-asset-packs-synthesis$': '<rootDir>/../../../generic-asset-packs/synthesis/src/index.ts',
    '^@bitcode/generic-asset-packs-synthesis/(.*)$': '<rootDir>/../../../generic-asset-packs/synthesis/src/$1',
    '^@bitcode/generic-asset-packs-synthesis$': '<rootDir>/../../../generic-asset-packs/synthesis/src/index.ts',    '^@bitcode/agent-generics/agents/factories$': '<rootDir>/../../../agent-generics/src/agents/factories.ts',
    '^@bitcode/agent-generics/types$': '<rootDir>/../../../agent-generics/src/types.ts',
    '^@bitcode/generic-llms$': '<rootDir>/../../../generic-llms/registry/src/index.ts',
    '^@bitcode/generic-llms/defaults$': '<rootDir>/../../../generic-llms/defaults/src/index.ts',
    '^@bitcode/generic-llms-defaults$': '<rootDir>/../../../generic-llms/defaults/src/index.ts',
    '^@bitcode/generic-llms-xai$': '<rootDir>/../../../generic-llms/xAI/src/index.ts',
    '^@bitcode/generic-llms-openai$': '<rootDir>/../../../generic-llms/OpenAI/src/index.ts',
    '^@bitcode/generic-llms-anthropic$': '<rootDir>/../../../generic-llms/Anthropic/src/index.ts',
    '^@bitcode/generic-llms-google$': '<rootDir>/../../../generic-llms/Google/src/index.ts',
    '^@bitcode/llm-generics$': '<rootDir>/../../../llm-generics/src/index.ts',
    '^@bitcode/llm-generics/(.*)$': '<rootDir>/../../../llm-generics/src/$1',
    '^@bitcode/logger$': '<rootDir>/../../../logger/src/index.ts',
    '^@bitcode/logger/(.*)$': '<rootDir>/../../../logger/src/$1',
    '^@bitcode/tools-generics$': '<rootDir>/../../../tools-generics/src/index.ts',
    '^@bitcode/tools-generics/(.*)$': '<rootDir>/../../../tools-generics/src/$1',
    '^@bitcode/vcs-generics$': '<rootDir>/../../../vcs-generics/src/index.ts',
    '^@bitcode/vcs-generics/(.*)$': '<rootDir>/../../../vcs-generics/src/$1',
    '^@bitcode/orm$': '<rootDir>/../../../orm/src/index.ts',
    '^@bitcode/orm/(.*)$': '<rootDir>/../../../orm/src/$1',
    '^@bitcode/prompts$': '<rootDir>/../../../prompts/src/index.ts',
    '^@bitcode/prompts/(.*)$': '<rootDir>/../../../prompts/src/$1',
    '^@bitcode/generic-tools/use-computer$': '<rootDir>/../../../generic-tools/use-computer/src/index.ts',
    '^@bitcode/generic-tools/use-computer/(.*)$': '<rootDir>/../../../generic-tools/use-computer/src/$1',
    '^@bitcode/registry$': '<rootDir>/../../../registry/src/index.ts',
    '^@bitcode/registry/(.*)$': '<rootDir>/../../../registry/src/$1',
    '^@bitcode/doc-comment-generics$': '<rootDir>/../../../doc-comment-generics/src/index.ts',
    '^@bitcode/doc-comment-generics/(.*)$': '<rootDir>/../../../doc-comment-generics/src/$1',
    '^@bitcode/btd/(.*)$': '<rootDir>/../../../btd/src/$1.ts',

    '^@bitcode/asset-packs-pipelines-domain$': '<rootDir>/../../domain/src/index.ts',
    '^@bitcode/asset-packs-pipelines-domain/(.*)$': '<rootDir>/../../domain/src/$1',
    '^@bitcode/asset-packs-pipelines-syntheses-domain$': '<rootDir>/src/index.ts',
    '^@bitcode/asset-packs-pipelines-syntheses-domain/(.*)$': '<rootDir>/src/$1',
    '^@bitcode/asset-packs-pipelines-execution-pipeline-sdivf-synthesize-reads-asset-packs$': '<rootDir>/../read/src/index.ts',
    '^@bitcode/asset-packs-pipelines-execution-pipeline-sdivf-synthesize-reads-asset-packs/(.*)$': '<rootDir>/../read/src/$1',
    '^@bitcode/asset-packs-pipelines-execution-pipeline-sdivf-synthesize-deposits-asset-packs$': '<rootDir>/../deposit/src/index.ts',
    '^@bitcode/asset-packs-pipelines-execution-pipeline-sdivf-synthesize-deposits-asset-packs/(.*)$': '<rootDir>/../deposit/src/$1',
    '^@bitcode/btd$': '<rootDir>/../../../btd/src/index.ts',
  },
};
