/*
 * Shared Notification & Event domain types used across the monorepo.
 *
 * NOTE:  This file purposefully lives inside the existing
 * `@bitcode/notifications` package so consumers can simply
 *   import { NotificationType, NotificationChannel, RunEvent, BtdBalanceEvent } from '@bitcode/notifications';
 * without having to learn yet-another alias.
 */

// ---------------------------------------------------------------------------
// High-level domain events emitted by Exchange execution services and BTD
// balance accounting code. These are not persisted; the Notification Worker
// fans them out into one-or-more Notification records.
// ---------------------------------------------------------------------------

export type RunLifecycle = 'STARTED' | 'SUCCESS' | 'ERROR';
export type BitcodeRunNotificationType = 'asset-pack' | 'need-measurement';

export interface RunEvent {
  kind: 'RUN';
  status: RunLifecycle;
  runId: number;
  runType: BitcodeRunNotificationType;
  userId: string;
  createdAt: string; // ISO-string for convenience
}

export interface BtdBalanceEvent {
  kind: 'BTD_BALANCE';
  type: 'LOW_BALANCE' | 'ZERO_BALANCE';
  userId: string;
  balance: number;
  threshold?: number; // only present for low balance
  createdAt: string;
}

export type DomainEvent = RunEvent | BtdBalanceEvent;

// ---------------------------------------------------------------------------
// Notification records – persisted in the `notifications` table so that the
// UI can render unread counts and history.  Each event may spawn multiple
// records (e.g. in-app + email).
// ---------------------------------------------------------------------------

export type NotificationType =
  | 'RUN_START'
  | 'RUN_SUCCESS'
  | 'RUN_ERROR'
  | 'LOW_BTD_BALANCE'
  | 'ZERO_BTD_BALANCE';

export type NotificationChannel = 'in_app' | 'email' | 'slack' | 'sms';

export interface NotificationPayload {
  // The shape varies per type but always has a `message` for convenience.
  message: string;
  // Optional Terminal deep-link URL (e.g. /executions/123)
  url?: string;
  // Arbitrary additional structured data
  [key: string]: any;
}

export interface NotificationRecord {
  id: string; // uuid – generated by DB
  user_id: string;
  type: NotificationType;
  channel: NotificationChannel;
  payload: NotificationPayload;
  read_at: string | null;
  created_at: string;
}
