/**
 * Shared doc-code-tool transform logic.
 *
 * The V26 admitted path is narrow:
 * attach a DocCodeToolPrompt to tool instances in a consistent way for both
 * build-time and compatibility runtime consumption.
 */

/**
 * Transform source code to inject doc-code-tool attachments.
 */
export function transformDocCodeTools(source: string, filename: string): string {
  const toolClassRegex = /\/\*\*([\s\S]*?)@doc-code-tool([\s\S]*?)\*\/\s*class\s+(\w+)\s+extends\s+Tool/g;
  const toolInstantiationRegex = /export\s+const\s+(\w+)\s*=\s*new\s+(\w+)\(\)/g;
  const promptPattern = /@prompt\s+(\w+)/;

  const toolPromptMap = new Map<string, string>();
  let match: RegExpExecArray | null;

  while ((match = toolClassRegex.exec(source)) !== null) {
    const afterTag = match[2];
    const className = match[3];

    const promptMatch = promptPattern.exec(afterTag);
    if (!promptMatch) {
      console.warn(`[doc-code-tool-loader] No @prompt found for ${className} in ${filename}`);
      continue;
    }

    toolPromptMap.set(className, promptMatch[1]);
  }

  if (toolPromptMap.size === 0) {
    return source;
  }

  let transformedSource = source;
  toolInstantiationRegex.lastIndex = 0;

  while ((match = toolInstantiationRegex.exec(source)) !== null) {
    const varName = match[1];
    const className = match[2];
    const promptName = toolPromptMap.get(className);

    if (!promptName) {
      continue;
    }

    const assignmentAlreadyPresent = new RegExp(`\\(${varName}\\s+as\\s+any\\)\\.__docCodePrompt`).test(transformedSource);
    if (assignmentAlreadyPresent) {
      continue;
    }

    const originalMatch = match[0];
    const replacement = `${originalMatch}

// Attach DocCodeToolPrompt for runtime injection (auto-generated by doc-code-tool-loader)
(${varName} as any).__docCodePrompt = ${promptName};
(${varName} as any).__promptParts = ${promptName};`;

    transformedSource = transformedSource.replace(originalMatch, replacement);
  }

  return transformedSource;
}
