// Polyfill fetch for the OpenAI library in non-browser test environments.
import 'openai/shims/node';

import Exa from 'exa-js';
import OpenAI from 'openai';

import { log } from '@bitcode/logger';

// Configurable match counts for Exa search results – callers can override via options.

// We support operating without an EXA credential by falling back to a mock client in
// development. Set ENGI_MOCK_EXA=true (or ENGI_MOCK_EXTERNAL=true) to force the mock.
type ExaClientLike = {
  searchAndContents: typeof Exa.prototype.searchAndContents;
  contents: typeof Exa.prototype.contents;
  findSimilar: typeof Exa.prototype.findSimilar;
};

class MockExaClient implements ExaClientLike {
  async searchAndContents(query: string): Promise<ExaSearchResponse> {
    return {
      results: [
        {
          title: `Mock result for "${query}"`,
          url: 'https://example.com/mock-result',
          score: 1,
          id: 'bitcode-mock-result',
          summary: 'Mock summary generated by Bitcode to unblock local development.',
          text: 'Mock body text generated by Bitcode.'
        }
      ],
      autopromptString: 'mock-autoprompt'
    };
  }

  async contents(ids: string[]): Promise<ExaContentsResponse> {
    return {
      results: ids.map((id, index) => ({
        title: `Mock contents for ${id}`,
        url: `https://example.com/mock-content/${index}`,
        score: 1,
        id
      }))
    };
  }

  async findSimilar(url: string): Promise<ExaSearchResponse> {
    return {
      results: [
        {
          title: `Mock similar result for ${url}`,
          url: `${url}?mock=1`,
          score: 1,
          id: 'bitcode-mock-similar'
        }
      ]
    };
  }
}

type MockReason = 'ENGI_MOCK_EXA' | 'ENGI_MOCK_EXTERNAL' | 'MISSING_API_KEY';

function parseBoolean(value: string | undefined): boolean {
  if (typeof value !== 'string') return false;
  const normalized = value.trim().toLowerCase();
  return normalized === 'true' || normalized === '1' || normalized === 'yes' || normalized === 'y' || normalized === 'on';
}

function getMockDecision(apiKey: string | undefined): { shouldMock: true; reason: MockReason } | { shouldMock: false } {
  if (parseBoolean(process.env.ENGI_MOCK_EXA)) {
    return { shouldMock: true, reason: 'ENGI_MOCK_EXA' };
  }

  if (parseBoolean(process.env.ENGI_MOCK_EXTERNAL)) {
    return { shouldMock: true, reason: 'ENGI_MOCK_EXTERNAL' };
  }

  if (!apiKey && process.env.NODE_ENV !== 'production') {
    return { shouldMock: true, reason: 'MISSING_API_KEY' };
  }

  return { shouldMock: false };
}

function createExaClient(): ExaClientLike {
  const apiKey = process.env.EXA_API_KEY ?? process.env.EXASEARCH_API_KEY;

  const decision = getMockDecision(apiKey);

  if (decision.shouldMock) {
    const reason =
      decision.reason === 'MISSING_API_KEY'
        ? 'missing API key'
        : `explicit mock flag (${decision.reason === 'ENGI_MOCK_EXA' ? 'ENGI_MOCK_EXA' : 'ENGI_MOCK_EXTERNAL'})`;

    log('Using mock Exa client for Bitcode ChatGPT App', 'warn', {
      reason,
      note: 'Set ENGI_MOCK_EXA=false and provide EXA_API_KEY to hit the real service.'
    });
    return new MockExaClient();
  }

  if (!apiKey) {
    throw new Error(
      'EXA_API_KEY (or EXASEARCH_API_KEY) must be provided. Set ENGI_MOCK_EXA=true to use the mock client in development.'
    );
  }

  return new Exa(apiKey);
}

// Initialize Exa client once per module load.
const exa = createExaClient();

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ExaResult {
  title: string;
  url: string;
  publishedDate?: string;
  author?: string;
  score: number;
  id: string;
  text?: string;
  highlights?: string[];
  highlightScores?: number[];
  summary?: string;
}

export interface ExaSearchResponse {
  results: ExaResult[];
  autopromptString?: string;
}

export interface ExaContentsResponse {
  results: ExaResult[];
}

export type SearchCategory =
  | 'company'
  | 'research paper'
  | 'news'
  | 'linkedin profile'
  | 'github'
  | 'tweet'
  | 'movie'
  | 'song'
  | 'personal site'
  | 'pdf'
  | 'financial report';

export type SearchType = 'keyword' | 'neural' | 'auto';

export interface ContentOptions {
  text?: {
    maxCharacters?: number;
    includeHtmlTags?: boolean;
  };
  highlights?: {
    numSentences?: number;
    highlightsPerUrl?: number;
    query?: string;
  };
  summary?: {
    query?: string;
  };
}

export interface SearchOptions {
  useAutoprompt?: boolean;
  type?: SearchType;
  category?: SearchCategory;
  numResults?: number;
  includeDomains?: string[];
  excludeDomains?: string[];
  startCrawlDate?: string;
  endCrawlDate?: string;
  startPublishedDate?: string;
  endPublishedDate?: string;
  includeText?: string[];
  excludeText?: string[];
  contents?: ContentOptions;
}

export interface GetContentsOptions {
  text?: {
    maxCharacters?: number;
    includeHtmlTags?: boolean;
  };
  highlights?: {
    numSentences?: number;
    highlightsPerUrl?: number;
    query?: string;
  };
  summary?: {
    query?: string;
  };
}

export interface FindSimilarOptions {
  numResults?: number;
  includeDomains?: string[];
  excludeDomains?: string[];
  startCrawlDate?: string;
  endCrawlDate?: string;
  startPublishedDate?: string;
  endPublishedDate?: string;
  includeText?: string[];
  excludeText?: string[];
  contents?: ContentOptions;
}

// ---------------------------------------------------------------------------
// Helper utilities
// ---------------------------------------------------------------------------

function logApiCall(action: string, params: Record<string, unknown>) {
  log(`Making Exa API ${action}`, 'debug', {
    params: JSON.stringify(params).slice(0, 500) + '...'
  });
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export async function search(
  query: string,
  options: SearchOptions = {}
): Promise<ExaSearchResponse> {
  logApiCall('search', { query, ...options });

  try {
    return await exa.searchAndContents(query, {
      useAutoprompt: options.useAutoprompt ?? true,
      type: options.type ?? 'neural',
      category: options.category,
      numResults: options.numResults ?? 10,
      includeDomains: options.includeDomains,
      excludeDomains: options.excludeDomains,
      startCrawlDate: options.startCrawlDate,
      endCrawlDate: options.endCrawlDate,
      startPublishedDate: options.startPublishedDate,
      endPublishedDate: options.endPublishedDate,
      includeText: options.includeText,
      excludeText: options.excludeText,
      text: options.contents?.text?.maxCharacters !== undefined,
      highlights: options.contents?.highlights !== undefined,
      summary: options.contents?.summary !== undefined
    });
  } catch (error) {
    log('Exa API search failed', 'error', {
      error: error instanceof Error ? error.message : String(error),
      query,
      options
    });
    throw error;
  }
}

export async function getContents(
  ids: string[],
  options: GetContentsOptions = {}
): Promise<ExaContentsResponse> {
  logApiCall('getContents', { ids, ...options });

  try {
    return await exa.contents(ids, {
      text: options.text !== undefined,
      highlights: options.highlights !== undefined,
      summary: options.summary !== undefined
    });
  } catch (error) {
    log('Exa API getContents failed', 'error', {
      error: error instanceof Error ? error.message : String(error),
      ids,
      options
    });
    throw error;
  }
}

export async function findSimilar(
  url: string,
  options: FindSimilarOptions = {}
): Promise<ExaSearchResponse> {
  logApiCall('findSimilar', { url, ...options });

  try {
    return await exa.findSimilar(url, {
      numResults: options.numResults ?? 10,
      includeDomains: options.includeDomains,
      excludeDomains: options.excludeDomains,
      startCrawlDate: options.startCrawlDate,
      endCrawlDate: options.endCrawlDate,
      startPublishedDate: options.startPublishedDate,
      endPublishedDate: options.endPublishedDate,
      includeText: options.includeText,
      excludeText: options.excludeText,
      text: options.contents?.text !== undefined,
      highlights: options.contents?.highlights !== undefined,
      summary: options.contents?.summary !== undefined
    });
  } catch (error) {
    log('Exa API findSimilar failed', 'error', {
      error: error instanceof Error ? error.message : String(error),
      url,
      options
    });
    throw error;
  }
}

// ---------------------------------------------------------------------------
// Utility helpers – kept from the original implementation
// ---------------------------------------------------------------------------

export function extractDomain(url: string): string | null {
  try {
    return new URL(url).hostname;
  } catch {
    return null;
  }
}

export function extractUrlsFromText(text: string): string[] {
  const urlRegex = /https?:\/\/[^\s<>"']+/g;
  return [...new Set(text.match(urlRegex) || [])];
}

// ---------------------------------------------------------------------------
// Advanced URL Intelligence System
// ---------------------------------------------------------------------------

export type UrlType = 
  | 'documentation'
  | 'github_repo'
  | 'github_issue'
  | 'stackoverflow'
  | 'api_reference'
  | 'tutorial'
  | 'blog_post'
  | 'npm_package'
  | 'pypi_package'
  | 'academic_paper'
  | 'news_article'
  | 'general';

export interface UrlClassification {
  url: string;
  type: UrlType;
  domain: string;
  confidence: number;
  metadata: {
    technology?: string[];
    language?: string[];
    framework?: string[];
    isOfficial?: boolean;
    authority?: 'high' | 'medium' | 'low';
  };
}

export interface UrlAttachmentAnalysis {
  classifications: UrlClassification[];
  suggestedDomains: string[];
  relatedDomains: string[];
  contentTopics: string[];
  searchStrategy: {
    includeDomains: string[];
    categories: SearchCategory[];
    enhancedQueries: string[];
  };
}

/**
 * Classify a URL into its type and extract metadata
 */
export function classifyUrl(url: string): UrlClassification {
  try {
    const urlObj = new URL(url);
    const domain = urlObj.hostname.toLowerCase();
    const path = urlObj.pathname.toLowerCase();
    const fullUrl = url.toLowerCase();

    // GitHub detection
    if (domain.includes('github.com')) {
      if (path.includes('/issues/') || path.includes('/pull/')) {
        return {
          url,
          type: 'github_issue',
          domain,
          confidence: 0.95,
          metadata: {
            isOfficial: false,
            authority: 'high'
          }
        };
      }
      return {
        url,
        type: 'github_repo',
        domain,
        confidence: 0.9,
        metadata: {
          isOfficial: false,
          authority: 'high'
        }
      };
    }

    // Documentation sites
    const docPatterns = [
      'docs.', 'documentation.', 'guide.', 'manual.', 'wiki.',
      '/docs/', '/documentation/', '/guide/', '/manual/'
    ];
    if (docPatterns.some(pattern => fullUrl.includes(pattern)) ||
        ['developer.mozilla.org', 'reactjs.org', 'vuejs.org', 'angular.io'].includes(domain)) {
      return {
        url,
        type: 'documentation',
        domain,
        confidence: 0.85,
        metadata: {
          isOfficial: domain.includes('developer.') || !domain.includes('www.'),
          authority: 'high'
        }
      };
    }

    // API References
    if (fullUrl.includes('/api/') || fullUrl.includes('api-') || domain.includes('api.')) {
      return {
        url,
        type: 'api_reference',
        domain,
        confidence: 0.8,
        metadata: {
          authority: 'high'
        }
      };
    }

    // Stack Overflow
    if (domain.includes('stackoverflow.com') || domain.includes('stackexchange.com')) {
      return {
        url,
        type: 'stackoverflow',
        domain,
        confidence: 0.95,
        metadata: {
          authority: 'high'
        }
      };
    }

    // Package repositories
    if (domain.includes('npmjs.com') || domain.includes('npm.')) {
      return {
        url,
        type: 'npm_package',
        domain,
        confidence: 0.9,
        metadata: {
          language: ['javascript', 'typescript'],
          authority: 'high'
        }
      };
    }

    if (domain.includes('pypi.org') || domain.includes('python.org/pypi')) {
      return {
        url,
        type: 'pypi_package',
        domain,
        confidence: 0.9,
        metadata: {
          language: ['python'],
          authority: 'high'
        }
      };
    }

    // Academic papers
    if (domain.includes('arxiv.org') || domain.includes('scholar.google') || 
        domain.includes('researchgate.net') || domain.includes('ieee.org')) {
      return {
        url,
        type: 'academic_paper',
        domain,
        confidence: 0.85,
        metadata: {
          authority: 'high'
        }
      };
    }

    // Tutorials and blogs
    const tutorialPatterns = ['tutorial', 'guide', 'howto', 'learn', 'course'];
    if (tutorialPatterns.some(pattern => fullUrl.includes(pattern))) {
      return {
        url,
        type: 'tutorial',
        domain,
        confidence: 0.7,
        metadata: {
          authority: domain.includes('medium.com') || domain.includes('dev.to') ? 'medium' : 'low'
        }
      };
    }

    // News and blogs
    const newsPatterns = ['news', 'blog', 'article', 'post'];
    if (newsPatterns.some(pattern => fullUrl.includes(pattern)) ||
        ['medium.com', 'dev.to', 'hashnode.com'].includes(domain)) {
      return {
        url,
        type: 'blog_post',
        domain,
        confidence: 0.6,
        metadata: {
          authority: 'medium'
        }
      };
    }

    return {
      url,
      type: 'general',
      domain,
      confidence: 0.5,
      metadata: {
        authority: 'low'
      }
    };
  } catch (error) {
    return {
      url,
      type: 'general',
      domain: 'unknown',
      confidence: 0.1,
      metadata: {
        authority: 'low'
      }
    };
  }
}

/**
 * Discover related domains based on a primary domain
 */
export function discoverRelatedDomains(domain: string): string[] {
  const relatedDomains: string[] = [];
  
  // Remove common prefixes and get base domain
  const baseDomain = domain.replace(/^(www\.|docs\.|api\.|developer\.|blog\.)/, '');
  
  // Add common subdomains
  const commonSubdomains = ['docs', 'api', 'developer', 'blog', 'wiki', 'support', 'help'];
  commonSubdomains.forEach(subdomain => {
    if (!domain.startsWith(subdomain)) {
      relatedDomains.push(`${subdomain}.${baseDomain}`);
    }
  });

  // Technology-specific related domains
  const techDomainMap: Record<string, string[]> = {
    'reactjs.org': ['react.dev', 'legacy.reactjs.org', 'beta.reactjs.org'],
    'vuejs.org': ['v3.vuejs.org', 'router.vuejs.org', 'pinia.vuejs.org'],
    'angular.io': ['angular.dev', 'material.angular.io'],
    'nodejs.org': ['npm.org', 'npmjs.com'],
    'python.org': ['pypi.org', 'docs.python.org'],
    'typescript.org': ['typescriptlang.org'],
    'mozilla.org': ['developer.mozilla.org'],
  };

  if (techDomainMap[baseDomain]) {
    relatedDomains.push(...techDomainMap[baseDomain]);
  }

  return [...new Set(relatedDomains)];
}

/**
 * Extract technology/framework keywords from URLs
 */
export function extractTechnologyContext(urls: string[]): string[] {
  const technologies = new Set<string>();
  
  const techPatterns = {
    react: /react/i,
    vue: /vue/i,
    angular: /angular/i,
    svelte: /svelte/i,
    nodejs: /node|npm/i,
    python: /python|pypi/i,
    javascript: /javascript|js/i,
    typescript: /typescript|ts/i,
    docker: /docker/i,
    kubernetes: /kubernetes|k8s/i,
    aws: /aws|amazon/i,
    gcp: /google.*cloud|gcp/i,
    azure: /azure|microsoft/i,
  };

  urls.forEach(url => {
    Object.entries(techPatterns).forEach(([tech, pattern]) => {
      if (pattern.test(url)) {
        technologies.add(tech);
      }
    });
  });

  return Array.from(technologies);
}

/**
 * Analyze URL attachments and generate enhanced search strategy
 */
export function analyzeUrlAttachments(urlAttachments: string[]): UrlAttachmentAnalysis {
  if (urlAttachments.length === 0) {
    return {
      classifications: [],
      suggestedDomains: [],
      relatedDomains: [],
      contentTopics: [],
      searchStrategy: {
        includeDomains: [],
        categories: [],
        enhancedQueries: []
      }
    };
  }

  // Classify all URLs
  const classifications = urlAttachments.map(classifyUrl);
  
  // Extract unique domains
  const domains = [...new Set(classifications.map(c => c.domain).filter(d => d !== 'unknown'))];
  
  // Discover related domains
  const relatedDomains = domains.flatMap(discoverRelatedDomains);
  
  // Extract technology context
  const contentTopics = extractTechnologyContext(urlAttachments);
  
  // Generate search categories based on URL types
  const categories: SearchCategory[] = [];
  if (classifications.some(c => c.type === 'github_repo' || c.type === 'github_issue')) {
    categories.push('github');
  }
  if (classifications.some(c => c.type === 'academic_paper')) {
    categories.push('research paper');
  }
  if (classifications.some(c => c.type === 'documentation')) {
    categories.push('pdf'); // Documentation often in PDF
  }

  // Generate enhanced queries based on URL content
  const enhancedQueries: string[] = [];
  
  // Add technology-specific queries
  contentTopics.forEach(tech => {
    enhancedQueries.push(`${tech} best practices implementation`);
    enhancedQueries.push(`${tech} common issues solutions`);
  });
  
  // Add type-specific queries
  const docUrls = classifications.filter(c => c.type === 'documentation');
  if (docUrls.length > 0) {
    enhancedQueries.push('official documentation implementation guide');
  }
  
  const repoUrls = classifications.filter(c => c.type === 'github_repo');
  if (repoUrls.length > 0) {
    enhancedQueries.push('similar implementation examples code');
  }

  return {
    classifications,
    suggestedDomains: domains,
    relatedDomains: [...new Set(relatedDomains)],
    contentTopics,
    searchStrategy: {
      includeDomains: [...domains, ...relatedDomains].slice(0, 10), // Limit to prevent over-scoping
      categories: [...new Set(categories)],
      enhancedQueries: [...new Set(enhancedQueries)]
    }
  };
}

/**
 * Enhanced search function that incorporates URL attachment intelligence
 */
export async function searchWithUrlIntelligence(
  query: string,
  urlAttachments: string[] = [],
  options: SearchOptions = {}
): Promise<ExaSearchResponse & { urlAnalysis?: UrlAttachmentAnalysis }> {
  let enhancedOptions = { ...options };
  let urlAnalysis: UrlAttachmentAnalysis | undefined;

  if (urlAttachments.length > 0) {
    urlAnalysis = analyzeUrlAttachments(urlAttachments);
    
    // Merge URL-derived domains with existing options
    const existingDomains = options.includeDomains || [];
    const urlDomains = urlAnalysis.searchStrategy.includeDomains;
    
    enhancedOptions = {
      ...options,
      includeDomains: [...new Set([...existingDomains, ...urlDomains])],
      // Use URL-suggested categories if none specified
      category: options.category || urlAnalysis.searchStrategy.categories[0]
    };
    
    log('Enhanced search with URL intelligence', 'info', {
      originalQuery: query,
      urlAttachments: urlAttachments.length,
      suggestedDomains: urlDomains.length,
      enhancedCategories: urlAnalysis.searchStrategy.categories
    });
  }

  const result = await search(query, enhancedOptions);
  
  return {
    ...result,
    urlAnalysis
  };
}

// ---------------------------------------------------------------------------
// Multi-Provider Search Export
// ---------------------------------------------------------------------------

export {
  multiProviderSearch,
  getProviderHealth,
  getProviderStatistics,
  shutdownOrchestrator
} from './orchestrator';

// Production-grade exports
export { 
  ProductionMultiProviderOrchestrator,
  productionMultiProviderSearch,
  getProductionOrchestrator,
  getProductionMetrics,
  getProductionHealth,
  shutdownProductionOrchestrator,
  type SearchMetrics
} from './production-orchestrator';

export {
  ResilienceCoordinator,
  CircuitBreaker,
  RetryStrategy,
  RateLimiter,
  ProviderHealthMonitor,
  FallbackManager,
  TimeoutManager,
  type ResilienceConfig,
  type CircuitBreakerConfig,
  type RetryConfig,
  type RateLimiterConfig,
  type FallbackConfig,
  type ProviderHealthMetrics
} from './resilience';

export {
  SearchProvider,
  SearchResult,
  SearchQuery,
  SearchOrchestrationResult,
  type MultiProviderSearchQuery,
  type MultiProviderSearchResult,
  type ProviderConfig
} from './multi-provider';
