"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateDigest = generateDigest;
async function generateDigest(_options) {
    return {
        productDocument: '###### What is this document?\n\nMock PRODUCT.md generated by digest.',
        agentDocument: '###### What is this document?\n\nMock AGENTS.md generated by digest.'
    };
}
