-- Migration: Create digests table for code-base digests metadata

create table if not exists public.digests (
  id          uuid primary key default gen_random_uuid(),
  org         text not null,
  repo        text not null,
  commit      text not null,
  url         text not null,
  stats       jsonb,
  created_at  timestamptz not null default now(),
  unique (org, repo, commit)
);

comment on table public.digests is 'Holds metadata & storage URL for per-commit codebase digests generated by Engi.';

comment on column public.digests.url   is 'Publicly accessible URL (S3 or Supabase Storage) pointing to the markdown digest file';
comment on column public.digests.stats is 'JSONB copy of key performance statistics returned by generateDigest – useful for debugging & insights.';