const path = require('path');
const { createJestConfig } = require('../../../tests/jest.base.cjs');
module.exports = createJestConfig(__dirname, {
  testMatch: ['**/__tests__/core/**/*.core.test.(ts|tsx)'],
  moduleNameMapper: {
    '^@bitcode/generic-measurements-absolutes-function-count$': path.join(__dirname, '../../generic-measurements/absolutes/function-count/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-type-count$': path.join(__dirname, '../../generic-measurements/absolutes/type-count/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-file-span$': path.join(__dirname, '../../generic-measurements/absolutes/file-span/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-symbolic-richness$': path.join(__dirname, '../../generic-measurements/absolutes/symbolic-richness/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-modularity$': path.join(__dirname, '../../generic-measurements/absolutes/modularity/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-lang-span$': path.join(__dirname, '../../generic-measurements/absolutes/lang-span/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-test-surface$': path.join(__dirname, '../../generic-measurements/absolutes/test-surface/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-api-surface$': path.join(__dirname, '../../generic-measurements/absolutes/api-surface/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-dependency-span$': path.join(__dirname, '../../generic-measurements/absolutes/dependency-span/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-doc-signal$': path.join(__dirname, '../../generic-measurements/absolutes/doc-signal/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-data-flow-depth$': path.join(__dirname, '../../generic-measurements/absolutes/data-flow-depth/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-symbol-connectivity$': path.join(__dirname, '../../generic-measurements/absolutes/symbol-connectivity/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-control-complexity$': path.join(__dirname, '../../generic-measurements/absolutes/control-complexity/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-config-surface$': path.join(__dirname, '../../generic-measurements/absolutes/config-surface/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-buildability$': path.join(__dirname, '../../generic-measurements/absolutes/buildability/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-test-pass-rate$': path.join(__dirname, '../../generic-measurements/absolutes/test-pass-rate/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-test-coverage$': path.join(__dirname, '../../generic-measurements/absolutes/test-coverage/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-test-strength$': path.join(__dirname, '../../generic-measurements/absolutes/test-strength/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-runtime-cleanliness$': path.join(__dirname, '../../generic-measurements/absolutes/runtime-cleanliness/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-reproducibility$': path.join(__dirname, '../../generic-measurements/absolutes/reproducibility/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-secret-safety$': path.join(__dirname, '../../generic-measurements/absolutes/secret-safety/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-pii-exposure$': path.join(__dirname, '../../generic-measurements/absolutes/pii-exposure/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-security-cleanliness$': path.join(__dirname, '../../generic-measurements/absolutes/security-cleanliness/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-dependency-health$': path.join(__dirname, '../../generic-measurements/absolutes/dependency-health/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-license-cleanliness$': path.join(__dirname, '../../generic-measurements/absolutes/license-cleanliness/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-duplication-internal$': path.join(__dirname, '../../generic-measurements/absolutes/duplication-internal/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-dead-code-ratio$': path.join(__dirname, '../../generic-measurements/absolutes/dead-code-ratio/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-originality$': path.join(__dirname, '../../generic-measurements/absolutes/originality/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-semantic-novelty$': path.join(__dirname, '../../generic-measurements/absolutes/semantic-novelty/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-contamination$': path.join(__dirname, '../../generic-measurements/absolutes/contamination/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-authorship-consistency$': path.join(__dirname, '../../generic-measurements/absolutes/authorship-consistency/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-provenance-integrity$': path.join(__dirname, '../../generic-measurements/absolutes/provenance-integrity/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-ai-generated-likelihood$': path.join(__dirname, '../../generic-measurements/absolutes/ai-generated-likelihood/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-correctness-estimate$': path.join(__dirname, '../../generic-measurements/absolutes/correctness-estimate/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-objectives-fidelity$': path.join(__dirname, '../../generic-measurements/absolutes/objectives-fidelity/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-computational-usage$': path.join(__dirname, '../../generic-measurements/absolutes/computational-usage/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-coherence$': path.join(__dirname, '../../generic-measurements/absolutes/coherence/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-completeness$': path.join(__dirname, '../../generic-measurements/absolutes/completeness/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-capability-clarity$': path.join(__dirname, '../../generic-measurements/absolutes/capability-clarity/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-documentation-alignment$': path.join(__dirname, '../../generic-measurements/absolutes/documentation-alignment/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-difficulty$': path.join(__dirname, '../../generic-measurements/absolutes/difficulty/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-irreducibility$': path.join(__dirname, '../../generic-measurements/absolutes/irreducibility/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-information-content$': path.join(__dirname, '../../generic-measurements/absolutes/information-content/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-rl-object-completeness$': path.join(__dirname, '../../generic-measurements/absolutes/rl-object-completeness/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-trajectory-richness$': path.join(__dirname, '../../generic-measurements/absolutes/trajectory-richness/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-diversity-contribution$': path.join(__dirname, '../../generic-measurements/absolutes/diversity-contribution/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-language-concentration$': path.join(__dirname, '../../generic-measurements/absolutes/language-concentration/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-framework-surface$': path.join(__dirname, '../../generic-measurements/absolutes/framework-surface/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-purpose-clarity$': path.join(__dirname, '../../generic-measurements/absolutes/purpose-clarity/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-dependency-class-balance$': path.join(__dirname, '../../generic-measurements/absolutes/dependency-class-balance/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-external-service-coupling$': path.join(__dirname, '../../generic-measurements/absolutes/external-service-coupling/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-contract-surface$': path.join(__dirname, '../../generic-measurements/absolutes/contract-surface/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-type-safety-pressure$': path.join(__dirname, '../../generic-measurements/absolutes/type-safety-pressure/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-observability-surface$': path.join(__dirname, '../../generic-measurements/absolutes/observability-surface/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-generated-code-mass$': path.join(__dirname, '../../generic-measurements/absolutes/generated-code-mass/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-test-as-spec$': path.join(__dirname, '../../generic-measurements/absolutes/test-as-spec/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-portability$': path.join(__dirname, '../../generic-measurements/absolutes/portability/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-architectural-pattern-density$': path.join(__dirname, '../../generic-measurements/absolutes/architectural-pattern-density/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-capability-surface$': path.join(__dirname, '../../generic-measurements/absolutes/capability-surface/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-copyleft-risk-mass$': path.join(__dirname, '../../generic-measurements/absolutes/copyleft-risk-mass/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-change-intent-clarity$': path.join(__dirname, '../../generic-measurements/absolutes/change-intent-clarity/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-data-architecture-clarity$': path.join(__dirname, '../../generic-measurements/absolutes/data-architecture-clarity/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-concurrency-model-clarity$': path.join(__dirname, '../../generic-measurements/absolutes/concurrency-model-clarity/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-api-style-clarity$': path.join(__dirname, '../../generic-measurements/absolutes/api-style-clarity/src/index.ts'),
    '^@bitcode/generic-measurements-absolutes-substitution-density$': path.join(__dirname, '../../generic-measurements/absolutes/substitution-density/src/index.ts'),
    '^@bitcode/generic-measurements-domain-data-pack-absolutes-catalog$': path.join(__dirname, '../../generic-measurements/domain/data-pack-absolutes-catalog/src/index.ts'),
    '^@bitcode/generic-measurements-shared-absolute-measure-input$': path.join(__dirname, '../../generic-measurements/shared/absolute-measure-input/src/index.ts'),
    '^@bitcode/measurement-generics$': path.join(__dirname, '../../measurement-generics/src/index.ts'),
  },
});
