/**
 * @doc-comment-developing-promptpartdevelopment
 * domain: output
 * intent: "Output specifications for Aurora PostgreSQL cloud database operations"
 * current_version: "GA1.02.1"
 * versions: []
 * benchmarks: [
 *   { "name": "enterprise_output_completeness", "test": "Does '{{content}}' provide complete enterprise database output specifications? Rate 0-1" },
 *   { "name": "cloud_infrastructure_insights", "test": "Does '{{content}}' deliver cloud infrastructure insights? Rate 0-1" },
 *   { "name": "critical_monitoring_data", "test": "Does '{{content}}' include critical monitoring and operational data? Rate 0-1" }
 * ]
 */

import { PromptPart } from '@bitcode/prompts';

export const PROMPTPART_SPECIFIC_TOOL_AURORAPOSTGRESMCP_DOCCODETOOLOUTPUT: PromptPart = 
  'Returns comprehensive Aurora PostgreSQL cluster status including: cluster_arn, cluster_identifier, engine, engine_version, database_name, master_username, db_cluster_members, allocated_storage, storage_encrypted, kms_key_id, vpc_security_groups, db_subnet_group, availability_zones, backup_retention_period, preferred_backup_window, preferred_maintenance_window, port, endpoint, reader_endpoint, custom_endpoints, multi_az, engine_mode, db_cluster_parameter_group, db_cluster_option_group_memberships, status, percent_progress, earliest_restorable_time, backup_policy, http_endpoint_enabled, activity_stream_status, associated_roles, iam_database_authentication_enabled, clone_group_id, cluster_create_time, earliest_backtrack_time, backtrack_window, backtrack_consumed_change_records, enabled_cloudwatch_logs_exports, capacity, scaling_configuration_info, deletion_protection, cross_account_clone, automatic_restart_time, serverless_v2_scaling_configuration, network_type, db_system_id, master_user_secret, io_optimized_next_allowed_modification_time, local_write_forwarding_status, aws_backup_recovery_point_arn, rds_custom_cluster_configuration, engine_lifecycle_support, performance_insights_enabled, performance_insights_kms_key_id, performance_insights_retention_period, serverless_v2_scaling_configuration, global_write_forwarding_status, global_write_forwarding_requested, pending_modified_values, db_cluster_instance_class, storage_type, iops, publicly_accessible, auto_minor_version_upgrade, monitoring_interval, monitoring_role_arn, enable_performance_insights, performance_insights_kms_key_id, performance_insights_retention_period, copy_tags_to_snapshot, tags, domain_memberships, and comprehensive CloudWatch metrics including CPU utilization, database connections, read/write IOPS, read/write latency, network throughput, free storage space, aurora_replica_lag, buffer_cache_hit_ratio, commit_latency, commit_throughput, database_connections, deadlocks, delete_latency, delete_throughput, ddl_latency, ddl_throughput, dml_latency, dml_throughput, engine_uptime, freeable_memory, free_local_storage, insert_latency, insert_throughput, login_failures, network_receive_throughput, network_transmit_throughput, queries, read_latency, read_throughput, result_set_cache_hit_ratio, select_latency, select_throughput, total_connections, update_latency, update_throughput, volume_bytes_used, volume_read_iops, volume_write_iops, and security compliance status reports.' as PromptPart;